#include <node_api.h>
#include <vek/vek_c.h>
#include <stdlib.h>
#include <string.h>

typedef struct { vek_runtime* runtime; } node_vek_runtime;
static napi_ref runtime_ctor;
static void ThrowLast(napi_env env,node_vek_runtime* self,const char* fallback){const char* e=self&&self->runtime?vek_last_error(self->runtime):fallback;napi_throw_error(env,NULL,(e&&*e)?e:fallback);}
static void FinalizeRuntime(napi_env env,void*data,void*hint){(void)env;(void)hint;node_vek_runtime*self=(node_vek_runtime*)data;if(self){if(self->runtime)vek_destroy(self->runtime);free(self);}}
static napi_value RuntimeNew(napi_env env,napi_callback_info info){napi_value thiz;size_t argc=0;napi_get_cb_info(env,info,&argc,NULL,&thiz,NULL);node_vek_runtime*self=(node_vek_runtime*)calloc(1,sizeof(*self));self->runtime=vek_create();if(!self->runtime){free(self);napi_throw_error(env,NULL,"VEK runtime creation failed");return NULL;}napi_wrap(env,thiz,self,FinalizeRuntime,NULL,NULL);return thiz;}
static node_vek_runtime* Unwrap(napi_env env,napi_callback_info info,napi_value* thiz,size_t* argc,napi_value* argv){napi_get_cb_info(env,info,argc,argv,thiz,NULL);node_vek_runtime*self=NULL;napi_unwrap(env,*thiz,(void**)&self);return self;}
static napi_value JsUndefined(napi_env env){napi_value v;napi_get_undefined(env,&v);return v;}
static napi_value RuntimeLoadFile(napi_env env,napi_callback_info info){napi_value thiz,args[1];size_t argc=1;node_vek_runtime*self=Unwrap(env,info,&thiz,&argc,args);if(!self||argc<1){napi_throw_type_error(env,NULL,"loadFile(path) requires a path");return NULL;}size_t n=0;napi_get_value_string_utf8(env,args[0],NULL,0,&n);char*buf=(char*)malloc(n+1);napi_get_value_string_utf8(env,args[0],buf,n+1,&n);int ok=vek_load_file(self->runtime,buf);free(buf);if(!ok){ThrowLast(env,self,"VEK load failed");return NULL;}return JsUndefined(env);}
static vek_value ToVek(napi_env env,napi_value v,char**storage){vek_value out={0};napi_valuetype t;napi_typeof(env,v,&t);if(t==napi_number){out.type=VEK_NUMBER;napi_get_value_double(env,v,&out.number);}else if(t==napi_boolean){bool b=false;out.type=VEK_BOOL;napi_get_value_bool(env,v,&b);out.boolean=b?1:0;}else if(t==napi_string){size_t n=0;napi_get_value_string_utf8(env,v,NULL,0,&n);*storage=(char*)malloc(n+1);napi_get_value_string_utf8(env,v,*storage,n+1,&n);out.type=VEK_STRING;out.string_value=*storage;}else{out.type=VEK_NIL;}return out;}
static napi_value FromVek(napi_env env,vek_value v){napi_value out;switch(v.type){case VEK_NUMBER:napi_create_double(env,v.number,&out);return out;case VEK_BOOL:napi_get_boolean(env,v.boolean!=0,&out);return out;case VEK_STRING:napi_create_string_utf8(env,v.string_value?v.string_value:"",NAPI_AUTO_LENGTH,&out);return out;case VEK_JSON:{napi_value json,parse,str;napi_get_global(env,&json);napi_get_named_property(env,json,"JSON",&json);napi_get_named_property(env,json,"parse",&parse);napi_create_string_utf8(env,v.string_value?v.string_value:"null",NAPI_AUTO_LENGTH,&str);napi_call_function(env,json,parse,1,&str,&out);return out;}default:napi_get_null(env,&out);return out;}}
static napi_value RuntimeCall(napi_env env,napi_callback_info info){napi_value thiz,args[32];size_t argc=32;node_vek_runtime*self=Unwrap(env,info,&thiz,&argc,args);if(!self||argc<1){napi_throw_type_error(env,NULL,"call(name, ...args) requires a function name");return NULL;}size_t nn=0;napi_get_value_string_utf8(env,args[0],NULL,0,&nn);char*name=(char*)malloc(nn+1);napi_get_value_string_utf8(env,args[0],name,nn+1,&nn);size_t count=argc-1;vek_value vals[31];char*storage[31]={0};for(size_t i=0;i<count;i++)vals[i]=ToVek(env,args[i+1],&storage[i]);vek_value r=vek_call(self->runtime,name,vals,count);free(name);for(size_t i=0;i<count;i++)free(storage[i]);if(r.type==VEK_NIL){const char*e=vek_last_error(self->runtime);if(e&&*e){ThrowLast(env,self,"VEK call failed");return NULL;}}return FromVek(env,r);}
static napi_value RuntimeVersion(napi_env env,napi_callback_info info){(void)info;napi_value out;napi_create_string_utf8(env,vek_version(),NAPI_AUTO_LENGTH,&out);return out;}
static napi_value Init(napi_env env,napi_value exports){napi_property_descriptor props[]={{"loadFile",0,RuntimeLoadFile,0,0,0,napi_default,0},{"call",0,RuntimeCall,0,0,0,napi_default,0},{"version",0,RuntimeVersion,0,0,0,napi_static,0}};napi_value ctor;napi_define_class(env,"Runtime",NAPI_AUTO_LENGTH,RuntimeNew,NULL,3,props,&ctor);napi_create_reference(env,ctor,1,&runtime_ctor);napi_set_named_property(env,exports,"Runtime",ctor);napi_value ver;napi_create_string_utf8(env,vek_version(),NAPI_AUTO_LENGTH,&ver);napi_set_named_property(env,exports,"version",ver);return exports;}
NAPI_MODULE(NODE_GYP_MODULE_NAME,Init)
