#!/usr/bin/env python3
"""VEK release version manager.

VERSION is the single source of truth. `sync` regenerates language-specific
version files. `check` verifies that generated files and release metadata agree.
"""
from __future__ import annotations
import argparse, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def read_version() -> str:
    v = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    if not SEMVER.fullmatch(v):
        raise SystemExit(f"Invalid VERSION: {v!r}")
    return v


def generated_go(name: str, version: str) -> str:
    return (
        "// Code generated by tools/version_manager.py from VERSION; DO NOT EDIT.\n"
        "package main\n\n"
        f'const {name} = "{version}"\n'
    )


def sync() -> None:
    v = read_version()
    files = {
        ROOT / "tools/github-installer/version_generated.go": generated_go("version", v),
        ROOT / "tools/portable-launcher/version_generated.go": generated_go("buildVersion", v),
        ROOT / "release-version.json": json.dumps(
            {
                "version": v,
                "tag": "v" + v,
                "windows_asset": f"VEK-v{v}-windows-x64.zip",
                "installer_asset": "VekInstaller.zip",
            },
            indent=2,
        )
        + "\n",
    }
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    print(f"VEK version files synchronized to {v}")


def check() -> None:
    v = read_version()
    errors: list[str] = []
    expected = {
        ROOT / "tools/github-installer/version_generated.go": f'const version = "{v}"',
        ROOT / "tools/portable-launcher/version_generated.go": f'const buildVersion = "{v}"',
    }
    for p, needle in expected.items():
        if not p.exists() or needle not in p.read_text(encoding="utf-8"):
            errors.append(f"{p.relative_to(ROOT)} is not synchronized to {v}")

    cm = (ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    if 'file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" VEK_VERSION' not in cm:
        errors.append("CMakeLists.txt does not source project version from VERSION")

    hdr = (ROOT / "include/vek/VekScriptEngine.h").read_text(encoding="utf-8")
    if "#define VEK_VERSION_STRING" in hdr:
        errors.append("VekScriptEngine.h still hard-codes VEK_VERSION_STRING")
    if "<vek/VekVersion.h>" not in hdr:
        errors.append("VekScriptEngine.h does not include generated VekVersion.h")

    rel_path = ROOT / "release-version.json"
    rel = json.loads(rel_path.read_text(encoding="utf-8")) if rel_path.exists() else {}
    if rel.get("version") != v or rel.get("tag") != "v" + v:
        errors.append("release-version.json is stale")

    if errors:
        print("VEK version consistency check FAILED:")
        for e in errors:
            print(" -", e)
        raise SystemExit(2)
    print(f"VEK version consistency check OK: {v}")


def set_version(v: str) -> None:
    if not SEMVER.fullmatch(v):
        raise SystemExit("Version must be MAJOR.MINOR.PATCH")
    (ROOT / "VERSION").write_text(v + "\n", encoding="utf-8")
    sync()
    check()


ap = argparse.ArgumentParser()
sub = ap.add_subparsers(dest="cmd", required=True)
sub.add_parser("sync")
sub.add_parser("check")
sp = sub.add_parser("set")
sp.add_argument("version")
a = ap.parse_args()
if a.cmd == "sync":
    sync()
elif a.cmd == "check":
    check()
else:
    set_version(a.version)
