#include "EditorCameraSystem.h"
#include "raymath.h"
#include <algorithm>
#include <cmath>
static float Approach(float c,float t,float d){if(c<t)return std::min(c+d,t);return std::max(c-d,t);}
Vector3 EditorCameraSystem::Forward()const{float yr=yaw*DEG2RAD,pr=pitch*DEG2RAD;return Vector3Normalize({sinf(yr)*cosf(pr),-sinf(pr),cosf(yr)*cosf(pr)});}Vector3 EditorCameraSystem::RightVec()const{float r=(yaw+90)*DEG2RAD;return{sinf(r),0,cosf(r)};}
void EditorCameraSystem::AimAt(Vector3 t){Vector3 d=Vector3Subtract(t,position);float l=Vector3Length(d);if(l<0.001f)return;targetYaw=atan2f(d.x,d.z)*RAD2DEG;targetPitch=-asinf(std::clamp(d.y/l,-1.0f,1.0f))*RAD2DEG;yaw=targetYaw;pitch=targetPitch;}
void EditorCameraSystem::ConfigureWorkspaceBounds(Vector3 c,Vector3 s,float maxH,float padding){boundsCenter=c;boundsSize=s;boundsMaxHeight=std::max(2.0f,maxH);boundsPadding=std::max(0.0f,padding);boundsEnabled=true;ClampToWorkspace();}
void EditorCameraSystem::ConfigureProfile(const vek::CameraProfileDefinition&p){profile=p;moveSpeed=profile.editorMoveSpeed;targetPitch=std::clamp(targetPitch,profile.editorPitchMin,profile.editorPitchMax);pitch=std::clamp(pitch,profile.editorPitchMin,profile.editorPitchMax);}
void EditorCameraSystem::ClampToWorkspace(){if(!boundsEnabled)return;float hx=std::max(1.0f,boundsSize.x*0.5f-boundsPadding),hz=std::max(1.0f,boundsSize.z*0.5f-boundsPadding);position.x=std::clamp(position.x,boundsCenter.x-hx,boundsCenter.x+hx);position.z=std::clamp(position.z,boundsCenter.z-hz,boundsCenter.z+hz);position.y=std::clamp(position.y,boundsCenter.y+0.75f,boundsCenter.y+std::max(1.5f,boundsMaxHeight-boundsPadding));}
void EditorCameraSystem::Enter(Vector3 f){active=true;orthographic=false;position=Vector3Add(f,{18,13,-22});ClampToWorkspace();AimAt(f);}void EditorCameraSystem::Exit(){active=false;}
void EditorCameraSystem::Update(float dt){if(!active)return;dt=std::clamp(dt,0.0f,0.05f);bool transformModifier=IsKeyDown(KEY_LEFT_ALT)||IsKeyDown(KEY_RIGHT_ALT);if(!transformModifier&&IsKeyDown(KEY_LEFT))targetYaw+=profile.editorYawSpeed*dt;if(!transformModifier&&IsKeyDown(KEY_RIGHT))targetYaw-=profile.editorYawSpeed*dt;if(!transformModifier&&IsKeyDown(KEY_UP))targetPitch-=profile.editorPitchSpeed*dt;if(!transformModifier&&IsKeyDown(KEY_DOWN))targetPitch+=profile.editorPitchSpeed*dt;
 if(profile.rmbLook&&IsMouseButtonDown(MOUSE_BUTTON_RIGHT)){Vector2 md=GetMouseDelta();targetYaw-=md.x*profile.yawSensitivity*profile.rmbYawScale;float sign=profile.invertMouseY?-1.0f:1.0f;targetPitch+=md.y*profile.pitchSensitivity*profile.rmbPitchScale*sign;}
 targetPitch=std::clamp(targetPitch,profile.editorPitchMin,profile.editorPitchMax);float wheel=GetMouseWheelMove();if(fabsf(wheel)>0.01f)moveSpeed=std::clamp(moveSpeed+wheel*2.0f,2.0f,80.0f);float speed=moveSpeed*(IsKeyDown(KEY_LEFT_SHIFT)||IsKeyDown(KEY_RIGHT_SHIFT)?profile.editorFastMultiplier:1.0f)*(IsKeyDown(KEY_LEFT_CONTROL)||IsKeyDown(KEY_RIGHT_CONTROL)?profile.editorFineMultiplier:1.0f);Vector3 move{0,0,0};if(IsKeyDown(KEY_W))move=Vector3Add(move,Forward());if(IsKeyDown(KEY_S))move=Vector3Subtract(move,Forward());if(IsKeyDown(KEY_D))move=Vector3Add(move,RightVec());if(IsKeyDown(KEY_A))move=Vector3Subtract(move,RightVec());if(IsKeyDown(KEY_E))move.y+=1;if(IsKeyDown(KEY_Q))move.y-=1;if(Vector3Length(move)>0.001f)position=Vector3Add(position,Vector3Scale(Vector3Normalize(move),speed*dt));yaw=Approach(yaw,targetYaw,std::max(180.0f,profile.maxYawSpeed)*dt);pitch=Approach(pitch,targetPitch,std::max(120.0f,profile.maxPitchSpeed)*dt);ClampToWorkspace();}
void EditorCameraSystem::Apply(Camera3D&c)const{c.position=position;c.target=Vector3Add(position,Vector3Scale(Forward(),10));c.up={0,1,0};c.fovy=orthographic?profile.editorOrthoSize:profile.editorFov;c.projection=orthographic?CAMERA_ORTHOGRAPHIC:CAMERA_PERSPECTIVE;}
void EditorCameraSystem::Focus(Vector3 p,float d){focusDistance=d;position=Vector3Subtract(p,Vector3Scale(Forward(),d));ClampToWorkspace();AimAt(p);}void EditorCameraSystem::FocusVehicle(Vector3 c,Vector3 s){float d=std::max({s.x,s.y,s.z,4.0f})*1.6f;position=Vector3Add(c,{d*0.8f,d*0.55f,-d});ClampToWorkspace();AimAt(c);}
void EditorCameraSystem::Front(Vector3 c,float d){position=Vector3Add(c,{0,3,-d});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::Rear(Vector3 c,float d){position=Vector3Add(c,{0,3,d});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::Left(Vector3 c,float d){position=Vector3Add(c,{-d,3,0});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::Right(Vector3 c,float d){position=Vector3Add(c,{d,3,0});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::Top(Vector3 c,float d){position=Vector3Add(c,{0,d,0.01f});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::Bottom(Vector3 c,float d){position=Vector3Add(c,{0,-d,0.01f});ClampToWorkspace();AimAt(c);}void EditorCameraSystem::ToggleOrthographic(){orthographic=!orthographic;}
