#include "Vehicle.h"
#include "PartPresentationRenderer.h"
#include "raymath.h"
#include "rlgl.h"
#include <algorithm>
#include <cmath>

static Vector3 RotateY(Vector3 p,float deg){float r=deg*DEG2RAD,c=cosf(r),s=sinf(r);return{p.x*c+p.z*s,p.y,-p.x*s+p.z*c};}
float Vehicle::TotalMass()const{float v=0;for(auto&p:parts)v+=p.mass;return std::max(200.0f,v);}float Vehicle::TotalPower()const{float v=0;for(auto&p:parts)v+=p.power+std::max(0.0f,p.thrust);return v*powerMultiplier;}int Vehicle::WheelCount()const{int n=0;for(auto&p:parts)if(PartIsWheel(p))n++;return n;}bool Vehicle::HasEngine()const{for(auto&p:parts)if(PartIsPowered(p))return true;return false;}bool Vehicle::HasSeat()const{for(auto&p:parts)if(p.isSeat||p.type==PartType::Seat)return true;return false;}bool Vehicle::ValidBuild()const{bool structural=false,movement=false;for(auto&p:parts){if(PartIsStructural(p))structural=true;if(PartIsMovement(p))movement=true;}return structural&&movement&&HasEngine()&&HasSeat();}float Vehicle::SpeedKph()const{return Vector3Length(velocity)*3.6f;}Vector3 Vehicle::Forward()const{float r=heading*DEG2RAD;return{sinf(r),0,cosf(r)};}
void Vehicle::UpdateDriving(float dt){if(!finalized)return;float throttle=(IsKeyDown(KEY_W)?1.0f:0.0f)-(IsKeyDown(KEY_S)?1.0f:0.0f);float steer=(IsKeyDown(KEY_D)?1.0f:0.0f)-(IsKeyDown(KEY_A)?1.0f:0.0f);float speed=Vector3Length(velocity);if(fuel>0&&fabsf(throttle)>0.01f&&WheelCount()>=3){float traction=1.0f;int wc=0;for(auto&p:parts)if(PartIsWheel(p)){traction+=p.traction;wc++;}if(wc)traction/=wc;float accel=(TotalPower()/TotalMass())*0.075f*std::clamp(traction,0.5f,1.6f);velocity=Vector3Add(velocity,Vector3Scale(Forward(),accel*throttle*dt));fuel-=fabsf(throttle)*dt*0.75f;if(fuel<0)fuel=0;}heading+=steer*70.0f*Clamp(speed/2.0f,0.0f,1.0f)*dt;float drag=0.35f+speed*0.018f;velocity=Vector3Scale(velocity,1.0f/(1.0f+drag*dt));if(IsKeyDown(KEY_SPACE))velocity=Vector3Scale(velocity,powf(0.045f,dt));position=Vector3Add(position,Vector3Scale(velocity,dt));position.y=0.7f;if(fabsf(position.x)>145||fabsf(position.z)>145)Reset();}
void Vehicle::Reset(){position={0,0.7f,10};velocity={0,0,0};heading=0;}void Vehicle::Upgrade(){powerMultiplier*=1.25f;}
Vector3 Vehicle::SeatWorldPosition()const{for(auto&p:parts)if(p.isSeat||p.type==PartType::Seat)return Vector3Add(position,RotateY(p.localPosition,heading));return Vector3Add(position,{0,0.8f,0});}Vector3 Vehicle::ForwardWorld()const{return Forward();}Vector3 Vehicle::RightWorld()const{return RotateY({1,0,0},heading);}Vector3 Vehicle::EntryWorldPosition()const{return Vector3Add(SeatWorldPosition(),Vector3Add(Vector3Scale(RightWorld(),1.35f),{0,-0.55f,0}));}
static Color ColorFor(const VehiclePart&p){if(p.visual=="light")return YELLOW;if(p.isWheel)return DARKGRAY;if(p.isSeat)return BROWN;if(p.category=="Aircraft")return SKYBLUE;if(p.category=="Marine")return Color{70,130,165,255};return Color{p.paintR,p.paintG,p.paintB,255};}
void Vehicle::Draw()const{if(!finalized)return;for(auto&p:parts){Vector3 w=Vector3Add(position,RotateY(p.localPosition,heading));Color c=ColorFor(p);PartPresentationRenderer::DrawModel(p,w,p.pitch,heading+p.yaw,p.roll,c,false,true);}}
