#include <vek/VekEditorSystems.h>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <sstream>

namespace vek {
GameModePolicy GameModeSystem::Policy(GameMode mode){GameModePolicy p;p.mode=mode;if(mode==GameMode::Sandbox){p.unlimitedMoney=p.unlimitedParts=p.allPartsUnlocked=p.infiniteFuel=p.freeRepairs=true;p.progressionEnabled=false;}return p;}
const char* GameModeSystem::Name(GameMode mode){return mode==GameMode::Sandbox?"Sandbox":"Survival";}

const std::vector<BuildPartDefinition>& BuildPartCatalog::All(){static const std::vector<BuildPartDefinition>p={
{0,"chassis","Basic Chassis",BuildPartCategory::Structural,300,250,0,1,false,false,false,false,true},{1,"wheel","Road Wheel",BuildPartCategory::Movement,25,80,0,1,false,true,false,false,false},{2,"engine_small","Small Engine",BuildPartCategory::Mechanical,120,400,22000,1,false,false,true,false,false},{3,"seat","Driver Seat",BuildPartCategory::Functional,20,100,0,1,false,false,false,true,false},{4,"frame","Frame Block",BuildPartCategory::Structural,55,60,0,1,false,false,false,false,true},{5,"beam","Steel Beam",BuildPartCategory::Structural,35,35,0,1,false,false,false,false,true},{6,"plate","Body Plate",BuildPartCategory::Structural,18,20,0,1,false,false,false,false,true},{7,"roll_cage","Roll Cage",BuildPartCategory::Structural,42,85,0,4,false,false,false,false,true},{8,"wing","Wing Section",BuildPartCategory::Aircraft,65,220,0,12,false,false,false,false,true},{9,"offroad_wheel","Off-road Wheel",BuildPartCategory::Movement,38,140,0,5,false,true,false,false,false},{10,"track","Track Module",BuildPartCategory::Movement,95,340,0,8,false,true,false,false,false},{11,"propeller","Propeller",BuildPartCategory::Aircraft,45,320,0,14,false,false,false,false,false},{12,"rotor","Rotor",BuildPartCategory::Aircraft,80,650,0,18,false,false,false,false,false},{13,"thruster","Thruster",BuildPartCategory::Experimental,55,900,18000,30,false,false,true,false,false},{14,"engine_diesel","Diesel Engine",BuildPartCategory::Mechanical,210,850,39000,6,false,false,true,false,false},{15,"electric_motor","Electric Motor",BuildPartCategory::Mechanical,95,700,30000,8,false,false,true,false,false},{16,"fuel_tank","Fuel Tank",BuildPartCategory::Mechanical,70,180,0,2,false,false,false,false,false},{17,"battery","Battery Pack",BuildPartCategory::Mechanical,85,260,0,8,false,false,false,false,false},{18,"suspension","Suspension Unit",BuildPartCategory::Mechanical,32,120,0,4,false,false,false,false,false},{19,"steering","Steering Unit",BuildPartCategory::Mechanical,20,95,0,2,false,false,false,false,false},{20,"light","Work Light",BuildPartCategory::Functional,5,30,0,1,false,false,false,false,false},{21,"cargo_box","Cargo Box",BuildPartCategory::Functional,55,140,0,3,false,false,false,false,false},{22,"tow_hook","Tow Hook",BuildPartCategory::Functional,18,80,0,4,false,false,false,false,false},{23,"winch","Winch",BuildPartCategory::Functional,48,230,0,7,false,false,false,false,false},{24,"tool_box","Tool Box",BuildPartCategory::Functional,24,75,0,2,false,false,false,false,false},{25,"jet_engine","Jet Engine",BuildPartCategory::Aircraft,240,3500,90000,30,false,false,true,false,false},{26,"hover_pad","Hover Pad",BuildPartCategory::Experimental,60,1200,12000,35,false,false,true,false,false},{27,"sandbox_reactor","Prototype Reactor",BuildPartCategory::Experimental,120,0,150000,1,true,false,true,false,false}};return p;}
const BuildPartDefinition*BuildPartCatalog::Find(int id){for(auto&p:All())if(p.id==id)return&p;return nullptr;}const BuildPartDefinition*BuildPartCatalog::Find(const std::string&k){for(auto&p:All())if(p.key==k)return&p;return nullptr;}std::vector<const BuildPartDefinition*>BuildPartCatalog::Category(BuildPartCategory c){std::vector<const BuildPartDefinition*>o;for(auto&p:All())if(p.category==c)o.push_back(&p);return o;}

static std::string Lower(std::string s){std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return(char)std::tolower(c);});return s;}
static VekVec3 Vec3From(const VekValue&v,VekVec3 f={}){if(!v.IsMap())return f;return{(float)v.Get("x").AsNumber(f.x),(float)v.Get("y").AsNumber(f.y),(float)v.Get("z").AsNumber(f.z)};}
static std::vector<std::string>StringsFrom(const VekValue&v){std::vector<std::string>o;if(auto*a=v.AsArray())for(auto&x:*a)o.push_back(x.AsString());return o;}
bool PartDefinition::HasTag(const std::string&t)const{return std::find(tags.begin(),tags.end(),t)!=tags.end();}
const PartComponentDefinition*PartDefinition::Component(const std::string&t)const{for(auto&c:components)if(c.type==t)return&c;return nullptr;}
float PartDefinition::ComponentNumber(const std::string&c,const std::string&k,float f)const{auto*p=Component(c);if(!p)return f;auto it=p->properties.find(k);return it==p->properties.end()?f:(float)it->second.AsNumber(f);}
std::string PartDefinition::ComponentString(const std::string&c,const std::string&k,const std::string&f)const{auto*p=Component(c);if(!p)return f;auto it=p->properties.find(k);return it==p->properties.end()?f:it->second.AsString();}

bool PartRegistry::RegisterPart(const PartDefinition&p){if(p.id.empty()||p.displayName.empty()||p.mass<0||p.price<0||p.size.x<=0||p.size.y<=0||p.size.z<=0)return false;auto it=index.find(p.id);if(it!=index.end()){parts[it->second]=p;return true;}index[p.id]=parts.size();parts.push_back(p);return true;}
bool PartRegistry::RegisterPartValue(const VekValue&v,std::string*error){if(!v.IsMap()){if(error)*error="part definition must be a map";return false;}PartDefinition p;p.id=v.Get("id").AsString();p.category=v.Get("category").AsString();if(p.category.empty())p.category="Structural";p.subcategory=v.Get("subcategory").AsString();p.displayName=v.Get("display_name").AsString();p.description=v.Get("description").AsString();p.visual=v.Get("visual").AsString();if(p.visual.empty())p.visual="box";p.mass=(float)v.Get("mass").AsNumber();p.price=(float)v.Get("price").AsNumber();p.durability=(float)v.Get("durability").AsNumber(100);p.unlockLevel=std::max(1,(int)v.Get("unlock_level").AsNumber(1));p.requiredTechnology=v.Get("technology").AsString();p.sandboxOnly=v.Get("sandbox_only").AsBool(false);p.size=Vec3From(v.Get("size"),{1,1,1});p.tags=StringsFrom(v.Get("tags"));
if(auto*a=v.Get("components").AsArray())for(auto&cv:*a){if(!cv.IsMap())continue;PartComponentDefinition c;c.type=cv.Get("type").AsString();if(auto*m=cv.Get("properties").AsMap())c.properties=*m;else if(auto*m=cv.AsMap()){for(auto&kv:*m)if(kv.first!="type")c.properties[kv.first]=kv.second;}if(!c.type.empty())p.components.push_back(std::move(c));}
if(auto*a=v.Get("attachments").AsArray())for(auto&av:*a){if(!av.IsMap())continue;PartAttachmentNode n;n.name=av.Get("name").AsString();n.type=av.Get("type").AsString();n.position=Vec3From(av.Get("position"));n.direction=Vec3From(av.Get("direction"),{0,1,0});n.compatibleTypes=StringsFrom(av.Get("compatible"));if(!n.type.empty())p.attachments.push_back(std::move(n));}
if(!RegisterPart(p)){if(error)*error="invalid or incomplete part: "+p.id;return false;}return true;}
const PartDefinition*PartRegistry::FindPart(const std::string&id)const{auto it=index.find(id);return it==index.end()?nullptr:&parts[it->second];}
std::vector<const PartDefinition*>PartRegistry::GetCategory(const std::string&c)const{std::vector<const PartDefinition*>o;for(auto&p:parts)if(c.empty()||p.category==c)o.push_back(&p);return o;}
std::vector<const PartDefinition*>PartRegistry::Search(const std::string&q,const std::string&cat)const{std::vector<const PartDefinition*>o;std::string lq=Lower(q);for(auto&p:parts){if(!cat.empty()&&p.category!=cat)continue;std::string hay=Lower(p.displayName+" "+p.id+" "+p.subcategory);for(auto&t:p.tags)hay+=" "+Lower(t);if(lq.empty()||hay.find(lq)!=std::string::npos)o.push_back(&p);}return o;}
const std::vector<PartDefinition>&PartRegistry::All()const{return parts;}void PartRegistry::Clear(){parts.clear();index.clear();}std::size_t PartRegistry::Size()const{return parts.size();}
void PartRegistry::RegisterNatives(VekScriptEngine&e){e.RegisterNative("part_register",[this](const std::vector<VekValue>&a){std::string err;return VekValue(!a.empty()&&RegisterPartValue(a[0],&err));});e.RegisterNative("part_clear",[this](const std::vector<VekValue>&){Clear();return VekValue(true);});e.RegisterNative("part_count",[this](const std::vector<VekValue>&){return VekValue((double)Size());});e.RegisterNative("component",[](const std::vector<VekValue>&a){VekMap m;m["type"]=a.empty()?VekValue(""):a[0];m["properties"]=a.size()>1?a[1]:VekValue::Map();return VekValue(std::move(m));});e.RegisterNative("attachment",[](const std::vector<VekValue>&a){VekMap m;m["name"]=a.size()>0?a[0]:VekValue("");m["type"]=a.size()>1?a[1]:VekValue("");m["position"]=a.size()>2?a[2]:VekValue::Map();m["direction"]=a.size()>3?a[3]:VekValue::Map();m["compatible"]=a.size()>4?a[4]:VekValue::Array();return VekValue(std::move(m));});}

VehicleEditorSystem::VehicleEditorSystem(VehicleEditorSettings s):settings(s){}const VehicleEditorSettings&VehicleEditorSystem::Settings()const{return settings;}void VehicleEditorSystem::SetSettings(const VehicleEditorSettings&s){settings=s;}float VehicleEditorSystem::Snap(float v,bool fine)const{float g=fine?settings.fineGridSize:settings.gridSize;return g<=0.0001f?v:std::round(v/g)*g;}bool VehicleEditorSystem::PositionInsideBuildArea(float x,float z)const{return std::fabs(x)<=settings.buildRadius&&std::fabs(z)<=settings.buildRadius;}int VehicleEditorSystem::MaxParts(GameMode m)const{return m==GameMode::Sandbox?settings.sandboxMaxParts:settings.survivalMaxParts;}bool VehicleEditorSystem::PartUnlocked(const BuildPartDefinition&p,GameMode m,int level)const{return m==GameMode::Sandbox||(!p.sandboxOnly&&level>=p.unlockLevel);}float VehicleEditorSystem::EffectivePartCost(const BuildPartDefinition&p,GameMode m)const{return m==GameMode::Sandbox?0:std::max(0.0f,p.cost);}BuildValidationResult VehicleEditorSystem::Validate(const VehicleBuildCounts&c,GameMode)const{BuildValidationResult r;if(c.structuralParts<1){r.primaryMessage="Add at least one structural part.";return r;}if(c.seats<1){r.primaryMessage="Add a driver seat.";return r;}if(c.engines<1){r.primaryMessage="Add propulsion.";return r;}if(c.wheels<3&&c.movementParts<1){r.primaryMessage="Add movement components.";return r;}if(c.mass>0&&c.power/c.mass<20)r.warnings.push_back("Low power-to-weight ratio.");r.valid=true;r.primaryMessage="Build ready.";return r;}
void VekRegisterVehicleEditorLibrary(VekScriptEngine&e){
 e.RegisterNative("mode_is_sandbox",[](const std::vector<VekValue>&a){return VekValue(!a.empty()&&a[0].AsString()=="sandbox");});
 e.RegisterNative("mode_part_cost",[](const std::vector<VekValue>&a){return VekValue(a.size()<2?0.0:(a[0].AsString()=="sandbox"?0.0:std::max(0.0,a[1].AsNumber())));});
 e.RegisterNative("editor_snap",[](const std::vector<VekValue>&a){if(a.size()<2)return VekValue(0.0);double g=a[1].AsNumber();return VekValue(g<=0.000001?a[0].AsNumber():std::round(a[0].AsNumber()/g)*g);});
 e.RegisterNative("editor_inside",[](const std::vector<VekValue>&a){if(a.size()<3)return VekValue(false);return VekValue(std::fabs(a[0].AsNumber())<=a[2].AsNumber()&&std::fabs(a[1].AsNumber())<=a[2].AsNumber());});
 e.RegisterNative("editor_inside_radius",[](const std::vector<VekValue>&a){if(a.size()<3)return VekValue(false);return VekValue(std::fabs(a[0].AsNumber())<=a[2].AsNumber()&&std::fabs(a[1].AsNumber())<=a[2].AsNumber());});
 e.RegisterNative("editor_power_to_weight",[](const std::vector<VekValue>&a){if(a.size()<2||a[0].AsNumber()<=0)return VekValue(0.0);return VekValue(a[1].AsNumber()/a[0].AsNumber());});
 e.RegisterNative("editor_basic_valid",[](const std::vector<VekValue>&a){if(a.size()<5)return VekValue(false);return VekValue(a[0].AsNumber()>=1&&a[1].AsNumber()>=1&&a[2].AsNumber()>=1&&(a[3].AsNumber()>=3||a[4].AsNumber()>=1));});
 e.RegisterNative("editor_part_unlocked",[](const std::vector<VekValue>&a){if(a.size()<4)return VekValue(false);bool sb=a[0].AsString()=="sandbox";return VekValue(sb||(!a[3].AsBool()&&a[1].AsNumber()>=a[2].AsNumber()));});
 e.RegisterNative("editor_max_parts",[](const std::vector<VekValue>&a){if(a.size()<3)return VekValue(96.0);return VekValue(a[0].AsString()=="sandbox"?a[2].AsNumber():a[1].AsNumber());});
}
} // namespace vek
