#include <vek/VekGuiFramework.h>
#include <vek/VekUiVirtualization.h>

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <limits>
#include <set>
#include <sstream>
#include <unordered_set>

namespace vek {
namespace {

float Finite(float v, float fallback = 0.0f) { return std::isfinite(v) ? v : fallback; }
float ClampNonNegative(float v) { return std::max(0.0f, Finite(v)); }
float Clamp01(float v) { return std::clamp(Finite(v, 1.0f), 0.0f, 1.0f); }
std::string Lower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); });
    return s;
}

GuiColor ParseHexColor(std::string s, GuiColor fallback) {
    if (s.empty() || s[0] != '#') return fallback;
    s.erase(s.begin());
    if (s.size() == 3 || s.size() == 4) {
        std::string expanded;
        for (char c : s) { expanded.push_back(c); expanded.push_back(c); }
        s = expanded;
    }
    if (s.size() != 6 && s.size() != 8) return fallback;
    auto byte = [&](std::size_t at)->int {
        char b[3] = {s[at], s[at+1], 0};
        char* end = nullptr; long v = std::strtol(b, &end, 16);
        return end && *end == 0 ? static_cast<int>(v) : -1;
    };
    int r=byte(0),g=byte(2),b=byte(4),a=s.size()==8?byte(6):255;
    if (r<0||g<0||b<0||a<0) return fallback;
    return {r/255.0f,g/255.0f,b/255.0f,a/255.0f};
}

GuiColor ColorFromValue(const VekValue& v, GuiColor fallback) {
    if (v.IsString()) return ParseHexColor(v.AsString(), fallback);
    if (!v.IsMap()) return fallback;
    fallback.r = static_cast<float>(v.Get("r").AsNumber(fallback.r));
    fallback.g = static_cast<float>(v.Get("g").AsNumber(fallback.g));
    fallback.b = static_cast<float>(v.Get("b").AsNumber(fallback.b));
    fallback.a = static_cast<float>(v.Get("a").AsNumber(fallback.a));
    fallback.r=Clamp01(fallback.r); fallback.g=Clamp01(fallback.g); fallback.b=Clamp01(fallback.b); fallback.a=Clamp01(fallback.a);
    return fallback;
}
GuiColor WithAlpha(GuiColor c, float a) { c.a = Clamp01(a); return c; }
GuiColor LerpColor(GuiColor a, GuiColor b, float t) {
    t=Clamp01(t); return {a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t,a.a+(b.a-a.a)*t};
}
VekValue ColorToValue(const GuiColor& c) { VekMap m; m["r"]=c.r;m["g"]=c.g;m["b"]=c.b;m["a"]=c.a;return VekValue(m); }
VekValue RectToValue(const GuiRectF& r) { VekMap m;m["x"]=r.x;m["y"]=r.y;m["width"]=r.width;m["height"]=r.height;return VekValue(m); }

GuiEdges EdgesFromValue(const VekValue& v, GuiEdges fallback={}) {
    if (v.IsNumber()) { float n=static_cast<float>(v.AsNumber()); return {n,n,n,n}; }
    if (v.IsArray()) {
        auto* a=v.AsArray();
        if (a->size()==2) { float y=static_cast<float>((*a)[0].AsNumber()),x=static_cast<float>((*a)[1].AsNumber()); return{x,y,x,y}; }
        if (a->size()==4) return{static_cast<float>((*a)[3].AsNumber()),static_cast<float>((*a)[0].AsNumber()),static_cast<float>((*a)[1].AsNumber()),static_cast<float>((*a)[2].AsNumber())};
    }
    if (!v.IsMap()) return fallback;
    fallback.left=static_cast<float>(v.Get("left").AsNumber(fallback.left));fallback.top=static_cast<float>(v.Get("top").AsNumber(fallback.top));
    fallback.right=static_cast<float>(v.Get("right").AsNumber(fallback.right));fallback.bottom=static_cast<float>(v.Get("bottom").AsNumber(fallback.bottom));
    return fallback;
}

GuiSizeMode ParseSizeMode(const std::string& value, GuiSizeMode fallback=GuiSizeMode::Content) {
    auto s=Lower(value); if(s=="fixed"||s=="px")return GuiSizeMode::Fixed;if(s=="content"||s=="auto")return GuiSizeMode::Content;if(s=="fill"||s=="grow")return GuiSizeMode::Fill;if(s=="percent"||s=="%")return GuiSizeMode::Percent;return fallback;
}
GuiLayoutMode ParseLayout(const std::string& value, GuiLayoutMode fallback=GuiLayoutMode::Column) {
    auto s=Lower(value);if(s=="absolute")return GuiLayoutMode::Absolute;if(s=="row"||s=="horizontal")return GuiLayoutMode::Row;if(s=="column"||s=="vertical")return GuiLayoutMode::Column;if(s=="grid")return GuiLayoutMode::Grid;if(s=="overlay"||s=="stack")return GuiLayoutMode::Overlay;if(s=="dock")return GuiLayoutMode::Dock;return fallback;
}
GuiAlign ParseAlign(const std::string& value, GuiAlign fallback=GuiAlign::Stretch) {
    auto s=Lower(value);if(s=="start"||s=="left"||s=="top")return GuiAlign::Start;if(s=="center")return GuiAlign::Center;if(s=="end"||s=="right"||s=="bottom")return GuiAlign::End;if(s=="stretch"||s=="fill")return GuiAlign::Stretch;return fallback;
}
GuiJustify ParseJustify(const std::string& value, GuiJustify fallback=GuiJustify::Start) {
    auto s=Lower(value);if(s=="start")return GuiJustify::Start;if(s=="center")return GuiJustify::Center;if(s=="end")return GuiJustify::End;if(s=="space_between"||s=="space-between")return GuiJustify::SpaceBetween;if(s=="space_around"||s=="space-around")return GuiJustify::SpaceAround;return fallback;
}
GuiOverflow ParseOverflow(const std::string& value, GuiOverflow fallback=GuiOverflow::Visible) {
    auto s=Lower(value);if(s=="visible")return GuiOverflow::Visible;if(s=="hidden"||s=="clip")return GuiOverflow::Hidden;if(s=="scroll_x"||s=="x")return GuiOverflow::ScrollX;if(s=="scroll_y"||s=="y")return GuiOverflow::ScrollY;if(s=="scroll"||s=="both")return GuiOverflow::ScrollBoth;return fallback;
}
GuiPositionMode ParsePosition(const std::string& value, GuiPositionMode fallback=GuiPositionMode::Flow) {
    auto s=Lower(value);if(s=="flow"||s=="relative")return GuiPositionMode::Flow;if(s=="absolute")return GuiPositionMode::Absolute;if(s=="fixed")return GuiPositionMode::Fixed;return fallback;
}
GuiEase ParseEase(const std::string& value) {
    auto s=Lower(value);if(s=="ease_in"||s=="in")return GuiEase::EaseIn;if(s=="ease_out"||s=="out")return GuiEase::EaseOut;if(s=="ease_in_out"||s=="in_out")return GuiEase::EaseInOut;if(s=="smooth"||s=="smoothstep")return GuiEase::SmoothStep;return GuiEase::Linear;
}
GuiAccessibilityRole ParseRole(const std::string& value) {
    static const std::unordered_map<std::string,GuiAccessibilityRole> m={{"window",GuiAccessibilityRole::Window},{"dialog",GuiAccessibilityRole::Dialog},{"group",GuiAccessibilityRole::Group},{"text",GuiAccessibilityRole::Text},{"button",GuiAccessibilityRole::Button},{"checkbox",GuiAccessibilityRole::Checkbox},{"radio",GuiAccessibilityRole::Radio},{"slider",GuiAccessibilityRole::Slider},{"text_field",GuiAccessibilityRole::TextField},{"list",GuiAccessibilityRole::List},{"list_item",GuiAccessibilityRole::ListItem},{"tree",GuiAccessibilityRole::Tree},{"tree_item",GuiAccessibilityRole::TreeItem},{"table",GuiAccessibilityRole::Table},{"row",GuiAccessibilityRole::Row},{"cell",GuiAccessibilityRole::Cell},{"image",GuiAccessibilityRole::Image},{"menu",GuiAccessibilityRole::Menu},{"menu_item",GuiAccessibilityRole::MenuItem},{"tab",GuiAccessibilityRole::Tab},{"tab_panel",GuiAccessibilityRole::TabPanel},{"progress",GuiAccessibilityRole::ProgressBar},{"status",GuiAccessibilityRole::Status},{"toolbar",GuiAccessibilityRole::Toolbar}};
    auto it=m.find(Lower(value));return it==m.end()?GuiAccessibilityRole::None:it->second;
}

void PatchDimension(GuiDimension& d,const VekValue& v) {
    if(v.IsNumber()){d.mode=GuiSizeMode::Fixed;d.value=static_cast<float>(v.AsNumber());return;} if(!v.IsMap())return;
    if(!v.Get("mode").IsNil())d.mode=ParseSizeMode(v.Get("mode").AsString(),d.mode);if(!v.Get("value").IsNil())d.value=static_cast<float>(v.Get("value").AsNumber(d.value));
    if(!v.Get("min").IsNil())d.min=static_cast<float>(v.Get("min").AsNumber(d.min));if(!v.Get("max").IsNil())d.max=static_cast<float>(v.Get("max").AsNumber(d.max));
    d.min=ClampNonNegative(d.min);d.max=std::max(d.min,ClampNonNegative(d.max));
}

void PatchVisual(GuiVisualStyle& s,const VekValue& v) {
    if(!v.IsMap())return;
    if(!v.Get("background").IsNil())s.background=ColorFromValue(v.Get("background"),s.background);if(!v.Get("foreground").IsNil())s.foreground=ColorFromValue(v.Get("foreground"),s.foreground);
    if(!v.Get("border").IsNil())s.border=ColorFromValue(v.Get("border"),s.border);if(!v.Get("accent").IsNil())s.accent=ColorFromValue(v.Get("accent"),s.accent);
    if(!v.Get("shadow_color").IsNil())s.shadowColor=ColorFromValue(v.Get("shadow_color"),s.shadowColor);if(!v.Get("focus_ring_color").IsNil())s.focusRingColor=ColorFromValue(v.Get("focus_ring_color"),s.focusRingColor);
    if(!v.Get("track_color").IsNil())s.trackColor=ColorFromValue(v.Get("track_color"),s.trackColor);if(!v.Get("thumb_color").IsNil())s.thumbColor=ColorFromValue(v.Get("thumb_color"),s.thumbColor);
    if(!v.Get("opacity").IsNil())s.opacity=Clamp01(static_cast<float>(v.Get("opacity").AsNumber(s.opacity)));if(!v.Get("border_width").IsNil())s.borderWidth=ClampNonNegative(static_cast<float>(v.Get("border_width").AsNumber(s.borderWidth)));
    if(!v.Get("radius").IsNil())s.radius=ClampNonNegative(static_cast<float>(v.Get("radius").AsNumber(s.radius)));if(!v.Get("border_radius").IsNil())s.radius=ClampNonNegative(static_cast<float>(v.Get("border_radius").AsNumber(s.radius)));
    if(!v.Get("font_size").IsNil())s.fontSize=std::clamp(static_cast<float>(v.Get("font_size").AsNumber(s.fontSize)),4.0f,512.0f);if(!v.Get("line_height").IsNil())s.lineHeight=std::clamp(static_cast<float>(v.Get("line_height").AsNumber(s.lineHeight)),0.5f,8.0f);
    if(!v.Get("letter_spacing").IsNil())s.letterSpacing=static_cast<float>(v.Get("letter_spacing").AsNumber(s.letterSpacing));if(!v.Get("font").IsNil())s.fontFamily=v.Get("font").AsString();if(!v.Get("font_family").IsNil())s.fontFamily=v.Get("font_family").AsString();
    if(!v.Get("icon").IsNil())s.icon=v.Get("icon").AsString();if(!v.Get("icon_size").IsNil())s.iconSize=ClampNonNegative(static_cast<float>(v.Get("icon_size").AsNumber(s.iconSize)));
    if(!v.Get("shadow_blur").IsNil())s.shadowBlur=ClampNonNegative(static_cast<float>(v.Get("shadow_blur").AsNumber(s.shadowBlur)));if(!v.Get("shadow_x").IsNil())s.shadowOffsetX=static_cast<float>(v.Get("shadow_x").AsNumber(s.shadowOffsetX));if(!v.Get("shadow_y").IsNil())s.shadowOffsetY=static_cast<float>(v.Get("shadow_y").AsNumber(s.shadowOffsetY));
    if(!v.Get("focus_ring_width").IsNil())s.focusRingWidth=ClampNonNegative(static_cast<float>(v.Get("focus_ring_width").AsNumber(s.focusRingWidth)));if(!v.Get("backdrop_blur").IsNil())s.backdropBlur=ClampNonNegative(static_cast<float>(v.Get("backdrop_blur").AsNumber(s.backdropBlur)));
    if(!v.Get("scale").IsNil())s.scale=std::clamp(static_cast<float>(v.Get("scale").AsNumber(s.scale)),0.1f,4.0f);if(!v.Get("translate_x").IsNil())s.translateX=static_cast<float>(v.Get("translate_x").AsNumber(s.translateX));if(!v.Get("translate_y").IsNil())s.translateY=static_cast<float>(v.Get("translate_y").AsNumber(s.translateY));
    if(!v.Get("transition_duration").IsNil())s.transitionDuration=std::clamp(static_cast<float>(v.Get("transition_duration").AsNumber(s.transitionDuration)),0.0f,10.0f);if(!v.Get("easing").IsNil())s.easing=v.Get("easing").AsString();
    if(!v.Get("z").IsNil())s.zIndex=static_cast<int>(v.Get("z").AsNumber(s.zIndex));if(!v.Get("z_index").IsNil())s.zIndex=static_cast<int>(v.Get("z_index").AsNumber(s.zIndex));
}
void ApplyStyleMap(GuiVisualStyle& s,const VekMap& m){PatchVisual(s,VekValue(m));}

float ResolveDimension(const GuiDimension& d,float available,float content) { float v=content;switch(d.mode){case GuiSizeMode::Fixed:v=d.value;break;case GuiSizeMode::Fill:v=available;break;case GuiSizeMode::Percent:v=available*std::clamp(d.value,0.0f,1.0f);break;case GuiSizeMode::Content:default:break;}return std::clamp(ClampNonNegative(v),d.min,std::max(d.min,d.max)); }
float EaseValue(GuiEase e,float t){t=std::clamp(t,0.0f,1.0f);switch(e){case GuiEase::EaseIn:return t*t;case GuiEase::EaseOut:return 1-(1-t)*(1-t);case GuiEase::EaseInOut:return t<.5f?2*t*t:1-std::pow(-2*t+2,2.0f)/2.0f;case GuiEase::SmoothStep:return t*t*(3-2*t);default:return t;}}

bool IsFocusableType(GuiWidgetType t) {
    switch(t){case GuiWidgetType::Button:case GuiWidgetType::IconButton:case GuiWidgetType::Toggle:case GuiWidgetType::Checkbox:case GuiWidgetType::Radio:case GuiWidgetType::Slider:case GuiWidgetType::RangeSlider:case GuiWidgetType::TextInput:case GuiWidgetType::TextArea:case GuiWidgetType::SearchBox:case GuiWidgetType::NumberInput:case GuiWidgetType::ComboBox:case GuiWidgetType::Dropdown:case GuiWidgetType::MenuItem:case GuiWidgetType::Keybind:case GuiWidgetType::ColorPicker:case GuiWidgetType::TabItem:case GuiWidgetType::TreeItem:case GuiWidgetType::Viewport:return true;default:return false;}
}
bool IsScrollable(const GuiNode& n) { return n.type==GuiWidgetType::Scroll||n.type==GuiWidgetType::List||n.type==GuiWidgetType::Tree||n.type==GuiWidgetType::Table||n.layout.overflow==GuiOverflow::ScrollX||n.layout.overflow==GuiOverflow::ScrollY||n.layout.overflow==GuiOverflow::ScrollBoth; }
bool IsTextInputType(GuiWidgetType t){return t==GuiWidgetType::TextInput||t==GuiWidgetType::TextArea||t==GuiWidgetType::SearchBox||t==GuiWidgetType::NumberInput;}

VekValue EventToValue(const GuiEvent& e){VekMap m;m["type"]=GuiEventTypeName(e.type);m["target"]=e.targetId;m["current_target"]=e.currentTargetId;m["x"]=e.pointer.x;m["y"]=e.pointer.y;m["key"]=e.key;m["text"]=e.text;m["value"]=e.value;m["checked"]=e.checked;m["data"]=e.data;return VekValue(m);}

GuiRectF Inset(GuiRectF r,float p){return{r.x+p,r.y+p,std::max(0.0f,r.width-2*p),std::max(0.0f,r.height-2*p)};}
GuiRectF ScaleRect(GuiRectF r,float s,float tx=0,float ty=0){float nw=r.width*s,nh=r.height*s;return{r.x+(r.width-nw)*.5f+tx,r.y+(r.height-nh)*.5f+ty,nw,nh};}

double NormalizedValue(const GuiNode& n,double value){double span=n.maxValue-n.minValue;if(span<=0)return 0;return std::clamp((value-n.minValue)/span,0.0,1.0);}

struct ContentExtents { float width = 0.0f; float height = 0.0f; };
ContentExtents MeasureContentExtents(const GuiNode& n, const std::unordered_map<std::string,GuiNode>& nodes) {
    float maxBottom=n.computed.y+n.computed.height,maxRight=n.computed.x+n.computed.width;
    for(const auto& cid:n.children){auto it=nodes.find(cid);if(it==nodes.end()||!it->second.visible)continue;maxBottom=std::max(maxBottom,it->second.computed.y+it->second.computed.height+n.scrollY);maxRight=std::max(maxRight,it->second.computed.x+it->second.computed.width+n.scrollX);}
    return {std::max(n.computed.width,maxRight-n.computed.x),std::max(n.computed.height,maxBottom-n.computed.y)};
}

GuiDrawCommand Cmd(GuiDrawType type,const GuiNode& n,const std::string& part,GuiRectF r,const GuiVisualStyle& style,int layer){GuiDrawCommand c;c.type=type;c.nodeId=n.id;c.part=part;c.rect=r;c.style=style;c.color=style.background;c.layer=layer;return c;}

} // namespace

bool GuiContains(const GuiRectF&r,GuiPoint p){return p.x>=r.x&&p.y>=r.y&&p.x<=r.x+r.width&&p.y<=r.y+r.height;}

GuiWidgetType ParseGuiWidgetType(const std::string& name) {
    static const std::unordered_map<std::string,GuiWidgetType> m={{"root",GuiWidgetType::Root},{"window",GuiWidgetType::Window},{"modal",GuiWidgetType::Modal},{"panel",GuiWidgetType::Panel},{"card",GuiWidgetType::Card},{"dock_space",GuiWidgetType::DockSpace},{"dock",GuiWidgetType::DockSpace},{"split_pane",GuiWidgetType::SplitPane},{"tabs",GuiWidgetType::TabView},{"tab_view",GuiWidgetType::TabView},{"tab",GuiWidgetType::TabItem},{"menu_bar",GuiWidgetType::MenuBar},{"menu",GuiWidgetType::Menu},{"menu_item",GuiWidgetType::MenuItem},{"toolbar",GuiWidgetType::ToolBar},{"status_bar",GuiWidgetType::StatusBar},{"label",GuiWidgetType::Label},{"rich_text",GuiWidgetType::RichText},{"button",GuiWidgetType::Button},{"icon_button",GuiWidgetType::IconButton},{"toggle",GuiWidgetType::Toggle},{"checkbox",GuiWidgetType::Checkbox},{"radio",GuiWidgetType::Radio},{"slider",GuiWidgetType::Slider},{"range_slider",GuiWidgetType::RangeSlider},{"progress",GuiWidgetType::Progress},{"spinner",GuiWidgetType::Spinner},{"text_input",GuiWidgetType::TextInput},{"text_area",GuiWidgetType::TextArea},{"search",GuiWidgetType::SearchBox},{"search_box",GuiWidgetType::SearchBox},{"number_input",GuiWidgetType::NumberInput},{"combo",GuiWidgetType::ComboBox},{"combo_box",GuiWidgetType::ComboBox},{"dropdown",GuiWidgetType::Dropdown},{"list",GuiWidgetType::List},{"list_item",GuiWidgetType::ListItem},{"tree",GuiWidgetType::Tree},{"tree_item",GuiWidgetType::TreeItem},{"table",GuiWidgetType::Table},{"table_row",GuiWidgetType::TableRow},{"table_cell",GuiWidgetType::TableCell},{"scroll",GuiWidgetType::Scroll},{"image",GuiWidgetType::Image},{"canvas",GuiWidgetType::Canvas},{"separator",GuiWidgetType::Separator},{"spacer",GuiWidgetType::Spacer},{"tooltip",GuiWidgetType::Tooltip},{"context_menu",GuiWidgetType::ContextMenu},{"popup",GuiWidgetType::Popup},{"toast",GuiWidgetType::Toast},{"badge",GuiWidgetType::Badge},{"property_grid",GuiWidgetType::PropertyGrid},{"color_picker",GuiWidgetType::ColorPicker},{"keybind",GuiWidgetType::Keybind},{"viewport",GuiWidgetType::Viewport},{"graph",GuiWidgetType::Graph},{"timeline",GuiWidgetType::Timeline}};
    auto it=m.find(Lower(name));return it==m.end()?GuiWidgetType::Panel:it->second;
}
const char* GuiWidgetTypeName(GuiWidgetType t){switch(t){case GuiWidgetType::Root:return"root";case GuiWidgetType::Window:return"window";case GuiWidgetType::Modal:return"modal";case GuiWidgetType::Panel:return"panel";case GuiWidgetType::Card:return"card";case GuiWidgetType::DockSpace:return"dock_space";case GuiWidgetType::SplitPane:return"split_pane";case GuiWidgetType::TabView:return"tab_view";case GuiWidgetType::TabItem:return"tab";case GuiWidgetType::MenuBar:return"menu_bar";case GuiWidgetType::Menu:return"menu";case GuiWidgetType::MenuItem:return"menu_item";case GuiWidgetType::ToolBar:return"toolbar";case GuiWidgetType::StatusBar:return"status_bar";case GuiWidgetType::Label:return"label";case GuiWidgetType::RichText:return"rich_text";case GuiWidgetType::Button:return"button";case GuiWidgetType::IconButton:return"icon_button";case GuiWidgetType::Toggle:return"toggle";case GuiWidgetType::Checkbox:return"checkbox";case GuiWidgetType::Radio:return"radio";case GuiWidgetType::Slider:return"slider";case GuiWidgetType::RangeSlider:return"range_slider";case GuiWidgetType::Progress:return"progress";case GuiWidgetType::Spinner:return"spinner";case GuiWidgetType::TextInput:return"text_input";case GuiWidgetType::TextArea:return"text_area";case GuiWidgetType::SearchBox:return"search_box";case GuiWidgetType::NumberInput:return"number_input";case GuiWidgetType::ComboBox:return"combo_box";case GuiWidgetType::Dropdown:return"dropdown";case GuiWidgetType::List:return"list";case GuiWidgetType::ListItem:return"list_item";case GuiWidgetType::Tree:return"tree";case GuiWidgetType::TreeItem:return"tree_item";case GuiWidgetType::Table:return"table";case GuiWidgetType::TableRow:return"table_row";case GuiWidgetType::TableCell:return"table_cell";case GuiWidgetType::Scroll:return"scroll";case GuiWidgetType::Image:return"image";case GuiWidgetType::Canvas:return"canvas";case GuiWidgetType::Separator:return"separator";case GuiWidgetType::Spacer:return"spacer";case GuiWidgetType::Tooltip:return"tooltip";case GuiWidgetType::ContextMenu:return"context_menu";case GuiWidgetType::Popup:return"popup";case GuiWidgetType::Toast:return"toast";case GuiWidgetType::Badge:return"badge";case GuiWidgetType::PropertyGrid:return"property_grid";case GuiWidgetType::ColorPicker:return"color_picker";case GuiWidgetType::Keybind:return"keybind";case GuiWidgetType::Viewport:return"viewport";case GuiWidgetType::Graph:return"graph";case GuiWidgetType::Timeline:return"timeline";default:return"panel";}}
const char* GuiEventTypeName(GuiEventType t){switch(t){case GuiEventType::Click:return"click";case GuiEventType::DoubleClick:return"double_click";case GuiEventType::Change:return"change";case GuiEventType::Submit:return"submit";case GuiEventType::Focus:return"focus";case GuiEventType::Blur:return"blur";case GuiEventType::PointerDown:return"pointer_down";case GuiEventType::PointerUp:return"pointer_up";case GuiEventType::PointerMove:return"pointer_move";case GuiEventType::PointerEnter:return"pointer_enter";case GuiEventType::PointerLeave:return"pointer_leave";case GuiEventType::Scroll:return"scroll";case GuiEventType::KeyDown:return"key_down";case GuiEventType::KeyUp:return"key_up";case GuiEventType::TextInput:return"text_input";case GuiEventType::DragStart:return"drag_start";case GuiEventType::Drag:return"drag";case GuiEventType::DragEnd:return"drag_end";case GuiEventType::Drop:return"drop";case GuiEventType::Open:return"open";case GuiEventType::Close:return"close";case GuiEventType::Select:return"select";default:return"none";}}

GuiFramework::GuiFramework() {
    // Compatibility themes still exist for callers using DefineTheme/SetTheme,
    // while the modern stylesheet is the visual source of truth.
    GuiTheme dark;dark.id="vek.dark";dark.base.background={0.043f,0.051f,0.067f,1};dark.base.foreground={0.96f,0.97f,0.98f,1};dark.base.border={0.18f,0.21f,0.27f,1};dark.base.accent={0.36f,0.66f,1.0f,1};dark.base.radius=9;dark.base.fontSize=14;themes_[dark.id]=dark;
    GuiTheme light=dark;light.id="vek.light";light.base.background={0.96f,0.97f,0.98f,1};light.base.foreground={0.11f,0.13f,0.16f,1};light.base.border={0.82f,0.85f,0.89f,1};themes_[light.id]=light;
    styleSheet_.Parse(ui::ModernUiStyleSheetSource());
    styleSheet_.SetActiveTheme("vek.modern.dark");
    activeTheme_="vek.modern.dark";
}

std::size_t GuiFramework::LoadStyleSheet(const std::string& source){auto n=styleSheet_.Parse(source);MarkDirty();return n;}

bool GuiFramework::ValidateParent(const std::string&id,const std::string&parent,std::string*error)const{if(parent.empty())return true;if(parent==id){if(error)*error="GUI node cannot parent itself";return false;}auto p=nodes_.find(parent);if(p==nodes_.end()){if(error)*error="GUI parent does not exist: "+parent;return false;}std::unordered_set<std::string>seen;std::string cur=parent;while(!cur.empty()){if(cur==id){if(error)*error="GUI parent cycle detected";return false;}if(!seen.insert(cur).second)break;auto it=nodes_.find(cur);if(it==nodes_.end())break;cur=it->second.parentId;}return true;}
void GuiFramework::DetachFromParent(const GuiNode&n){if(n.parentId.empty())return;auto it=nodes_.find(n.parentId);if(it==nodes_.end())return;auto&c=it->second.children;c.erase(std::remove(c.begin(),c.end(),n.id),c.end());}
void GuiFramework::AttachToParent(const GuiNode&n){if(n.parentId.empty())return;auto it=nodes_.find(n.parentId);if(it==nodes_.end())return;auto&c=it->second.children;if(std::find(c.begin(),c.end(),n.id)==c.end())c.push_back(n.id);}
void GuiFramework::MarkDirty(){layoutDirty_=true;++revision_;}

bool GuiFramework::Create(const GuiNode&input,std::string*error){if(input.id.empty()||input.id.size()>192){if(error)*error="GUI id is empty or too long";return false;}if(nodes_.size()>=MaxNodes&&!nodes_.count(input.id)){if(error)*error="GUI node limit reached";return false;}if(nodes_.count(input.id)){if(error)*error="GUI id already exists: "+input.id;return false;}if(!ValidateParent(input.id,input.parentId,error))return false;GuiNode n=input;if(IsFocusableType(n.type)&&!n.focusable)n.focusable=true;n.children.clear();nodes_.emplace(n.id,n);AttachToParent(nodes_.at(n.id));MarkDirty();return true;}

bool GuiFramework::ApplyPatch(GuiNode&n,const VekValue&p,std::string*error){
    if(!p.IsMap()){if(error)*error="GUI patch must be a map";return false;}
    if(!p.Get("text").IsNil())n.text=p.Get("text").AsString();if(!p.Get("tooltip").IsNil())n.tooltip=p.Get("tooltip").AsString();if(!p.Get("image").IsNil())n.image=p.Get("image").AsString();if(!p.Get("binding").IsNil())n.dataBinding=p.Get("binding").AsString();
    if(!p.Get("visible").IsNil())n.visible=p.Get("visible").AsBool();if(!p.Get("enabled").IsNil())n.enabled=p.Get("enabled").AsBool();if(!p.Get("focusable").IsNil())n.focusable=p.Get("focusable").AsBool();if(!p.Get("draggable").IsNil())n.draggable=p.Get("draggable").AsBool();if(!p.Get("droppable").IsNil())n.droppable=p.Get("droppable").AsBool();if(!p.Get("clip_children").IsNil())n.clipChildren=p.Get("clip_children").AsBool();if(!p.Get("virtualized").IsNil())n.virtualized=p.Get("virtualized").AsBool();
    if(!p.Get("checked").IsNil())n.checked=p.Get("checked").AsBool();if(!p.Get("selected").IsNil())n.selected=p.Get("selected").AsBool();if(!p.Get("expanded").IsNil())n.expanded=p.Get("expanded").AsBool();if(!p.Get("invalid").IsNil())n.invalid=p.Get("invalid").AsBool();if(!p.Get("warning").IsNil())n.warning=p.Get("warning").AsBool();if(!p.Get("success").IsNil())n.success=p.Get("success").AsBool();
    if(!p.Get("value").IsNil())n.value=p.Get("value").AsNumber(n.value);if(!p.Get("value2").IsNil())n.value2=p.Get("value2").AsNumber(n.value2);if(!p.Get("min").IsNil())n.minValue=p.Get("min").AsNumber(n.minValue);if(!p.Get("max").IsNil())n.maxValue=p.Get("max").AsNumber(n.maxValue);if(!p.Get("step").IsNil())n.step=p.Get("step").AsNumber(n.step);if(!p.Get("selected_index").IsNil())n.selectedIndex=(int)p.Get("selected_index").AsNumber(n.selectedIndex);if(!p.Get("scroll_x").IsNil())n.scrollX=(float)p.Get("scroll_x").AsNumber(n.scrollX);if(!p.Get("scroll_y").IsNil())n.scrollY=(float)p.Get("scroll_y").AsNumber(n.scrollY);if(!p.Get("data").IsNil())n.data=p.Get("data");
    if(auto a=p.Get("classes");a.IsArray()){n.classes.clear();for(const auto&x:*a.AsArray())n.classes.push_back(x.AsString());}
    auto l=p.Get("layout");if(l.IsMap()){if(!l.Get("mode").IsNil())n.layout.mode=ParseLayout(l.Get("mode").AsString(),n.layout.mode);if(!l.Get("position").IsNil())n.layout.position=ParsePosition(l.Get("position").AsString(),n.layout.position);if(!l.Get("width").IsNil())PatchDimension(n.layout.width,l.Get("width"));if(!l.Get("height").IsNil())PatchDimension(n.layout.height,l.Get("height"));if(!l.Get("margin").IsNil())n.layout.margin=EdgesFromValue(l.Get("margin"),n.layout.margin);if(!l.Get("padding").IsNil())n.layout.padding=EdgesFromValue(l.Get("padding"),n.layout.padding);if(!l.Get("gap").IsNil())n.layout.gap=ClampNonNegative((float)l.Get("gap").AsNumber(n.layout.gap));if(!l.Get("columns").IsNil())n.layout.gridColumns=std::max(1,(int)l.Get("columns").AsNumber(n.layout.gridColumns));if(!l.Get("align").IsNil())n.layout.alignItems=ParseAlign(l.Get("align").AsString(),n.layout.alignItems);if(!l.Get("align_self").IsNil())n.layout.alignSelf=ParseAlign(l.Get("align_self").AsString(),n.layout.alignSelf);if(!l.Get("justify").IsNil())n.layout.justify=ParseJustify(l.Get("justify").AsString(),n.layout.justify);if(!l.Get("overflow").IsNil())n.layout.overflow=ParseOverflow(l.Get("overflow").AsString(),n.layout.overflow);if(!l.Get("aspect").IsNil())n.layout.aspectRatio=(float)l.Get("aspect").AsNumber(n.layout.aspectRatio);if(!l.Get("x").IsNil())n.layout.absoluteX=(float)l.Get("x").AsNumber(n.layout.absoluteX);if(!l.Get("y").IsNil())n.layout.absoluteY=(float)l.Get("y").AsNumber(n.layout.absoluteY);}
    if(!p.Get("style").IsNil()){PatchVisual(n.visual,p.Get("style"));n.hasVisual=true;}if(!p.Get("hover_style").IsNil()){PatchVisual(n.hoverVisual,p.Get("hover_style"));n.hasHoverVisual=true;}if(!p.Get("pressed_style").IsNil()){PatchVisual(n.pressedVisual,p.Get("pressed_style"));n.hasPressedVisual=true;}if(!p.Get("focus_style").IsNil()){PatchVisual(n.focusVisual,p.Get("focus_style"));n.hasFocusVisual=true;}if(!p.Get("disabled_style").IsNil()){PatchVisual(n.disabledVisual,p.Get("disabled_style"));n.hasDisabledVisual=true;}
    auto ac=p.Get("accessibility");if(ac.IsMap()){if(!ac.Get("role").IsNil())n.accessibility.role=ParseRole(ac.Get("role").AsString());if(!ac.Get("label").IsNil())n.accessibility.label=ac.Get("label").AsString();if(!ac.Get("hint").IsNil())n.accessibility.hint=ac.Get("hint").AsString();if(!ac.Get("value").IsNil())n.accessibility.valueText=ac.Get("value").AsString();if(!ac.Get("order").IsNil())n.accessibility.navigationOrder=(int)ac.Get("order").AsNumber();if(!ac.Get("hidden").IsNil())n.accessibility.hidden=ac.Get("hidden").AsBool();}
    if(n.maxValue<n.minValue)std::swap(n.maxValue,n.minValue);n.value=std::clamp(n.value,n.minValue,n.maxValue);n.value2=std::clamp(n.value2,n.minValue,n.maxValue);return true;
}

bool GuiFramework::CreateValue(const VekValue&v,std::string*error){if(!v.IsMap()){if(error)*error="GUI definition must be a map";return false;}GuiNode n;n.id=v.Get("id").AsString();n.type=v.Get("type").IsNil()?GuiWidgetType::Panel:ParseGuiWidgetType(v.Get("type").AsString());n.parentId=v.Get("parent").IsNil()?std::string{}:v.Get("parent").AsString();if(!ApplyPatch(n,v,error))return false;return Create(n,error);}
bool GuiFramework::Patch(const std::string&id,const VekValue&p,std::string*error){auto it=nodes_.find(id);if(it==nodes_.end()){if(error)*error="GUI node not found: "+id;return false;}std::string newParent=it->second.parentId;if(!p.Get("parent").IsNil())newParent=p.Get("parent").AsString();if(newParent!=it->second.parentId&&!ValidateParent(id,newParent,error))return false;std::string oldParent=it->second.parentId;if(!ApplyPatch(it->second,p,error))return false;if(newParent!=oldParent){DetachFromParent(it->second);it->second.parentId=newParent;AttachToParent(it->second);}MarkDirty();return true;}
bool GuiFramework::Reparent(const std::string&id,const std::string&parent,std::string*error){VekMap p;p["parent"]=parent;return Patch(id,VekValue(p),error);}
bool GuiFramework::Remove(const std::string&id,bool recursive){auto it=nodes_.find(id);if(it==nodes_.end())return false;if(!recursive&&!it->second.children.empty())return false;auto children=it->second.children;for(const auto&c:children)Remove(c,true);GuiNode copy=it->second;DetachFromParent(copy);nodes_.erase(id);if(focusedId_==id)focusedId_.clear();if(hoveredId_==id)hoveredId_.clear();if(pressedId_==id)pressedId_.clear();if(dragId_==id)dragId_.clear();animations_.erase(std::remove_if(animations_.begin(),animations_.end(),[&](const GuiAnimation&a){return a.nodeId==id;}),animations_.end());MarkDirty();return true;}
void GuiFramework::Clear(){nodes_.clear();events_.clear();animations_.clear();focusedId_.clear();hoveredId_.clear();pressedId_.clear();dragId_.clear();MarkDirty();}
GuiNode*GuiFramework::Find(const std::string&id){auto it=nodes_.find(id);return it==nodes_.end()?nullptr:&it->second;}const GuiNode*GuiFramework::Find(const std::string&id)const{auto it=nodes_.find(id);return it==nodes_.end()?nullptr:&it->second;}
std::vector<std::string>GuiFramework::ChildrenOf(const std::string&p)const{auto it=nodes_.find(p);return it==nodes_.end()?std::vector<std::string>{}:it->second.children;}
std::vector<std::string>GuiFramework::Roots()const{std::vector<std::string>r;for(auto&[id,n]:nodes_)if(n.parentId.empty())r.push_back(id);std::sort(r.begin(),r.end());return r;}

bool GuiFramework::DefineTheme(const GuiTheme&t,std::string*error){if(t.id.empty()||t.id.size()>128){if(error)*error="GUI theme id invalid";return false;}themes_[t.id]=t;++revision_;return true;}
bool GuiFramework::DefineThemeValue(const VekValue&v,std::string*error){if(!v.IsMap()){if(error)*error="GUI theme must be a map";return false;}GuiTheme t;t.id=v.Get("id").AsString();PatchVisual(t.base,v.Get("base"));auto vars=v.Get("variables");if(vars.IsMap())for(auto&[k,x]:*vars.AsMap())t.variables[k]=x;auto classes=v.Get("classes");if(classes.IsMap())for(auto&[k,x]:*classes.AsMap()){GuiVisualStyle s=t.base;PatchVisual(s,x);t.classes[k]=s;}return DefineTheme(t,error);}
bool GuiFramework::SetTheme(const std::string&id){
    if(styleSheet_.HasTheme(id)){styleSheet_.SetActiveTheme(id);activeTheme_=id;MarkDirty();return true;}
    if(id=="vek.dark"&&styleSheet_.HasTheme("vek.modern.dark")){styleSheet_.SetActiveTheme("vek.modern.dark");activeTheme_=id;MarkDirty();return true;}
    if(id=="vek.light"&&styleSheet_.HasTheme("vek.modern.light")){styleSheet_.SetActiveTheme("vek.modern.light");activeTheme_=id;MarkDirty();return true;}
    if(!themes_.count(id))return false;activeTheme_=id;MarkDirty();return true;
}
void GuiFramework::SetViewport(const GuiViewport&v){viewport_=v;viewport_.width=std::clamp(Finite(v.width,1280),1.0f,65536.0f);viewport_.height=std::clamp(Finite(v.height,720),1.0f,65536.0f);viewport_.dpiScale=std::clamp(Finite(v.dpiScale,1),0.25f,8.0f);MarkDirty();}

std::vector<ui::StyleNodeContext> GuiFramework::StylePath(const GuiNode&node)const{
    std::vector<const GuiNode*> rev;const GuiNode*cur=&node;std::unordered_set<std::string>seen;
    while(cur){rev.push_back(cur);if(cur->parentId.empty()||!seen.insert(cur->id).second)break;auto it=nodes_.find(cur->parentId);cur=it==nodes_.end()?nullptr:&it->second;}
    std::reverse(rev.begin(),rev.end());std::vector<ui::StyleNodeContext> path;path.reserve(rev.size());
    for(auto*n:rev){ui::StyleNodeContext c;c.type=GuiWidgetTypeName(n->type);c.id=n->id;c.classes=n->classes;if(n->hovered)c.pseudoStates.push_back("hover");if(n->pressed)c.pseudoStates.push_back("pressed");if(n->focused)c.pseudoStates.push_back("focused");if(n->focusVisible)c.pseudoStates.push_back("focus-visible");if(n->selected)c.pseudoStates.push_back("selected");if(n->checked)c.pseudoStates.push_back("checked");if(!n->enabled)c.pseudoStates.push_back("disabled");if(n->expanded)c.pseudoStates.push_back("expanded");if(n->dragging)c.pseudoStates.push_back("dragging");if(n->dropTarget)c.pseudoStates.push_back("drop-target");if(n->invalid)c.pseudoStates.push_back("invalid");if(n->warning)c.pseudoStates.push_back("warning");if(n->success)c.pseudoStates.push_back("success");path.push_back(std::move(c));}
    return path;
}
VekMap GuiFramework::ResolveStyleMap(const GuiNode&node)const { return modernStyleEnabled_ ? styleSheet_.Resolve(StylePath(node)) : VekMap{}; }
GuiVisualStyle GuiFramework::ResolveVisual(const GuiNode&n)const{
    GuiVisualStyle s;
    if(modernStyleEnabled_)ApplyStyleMap(s,ResolveStyleMap(n));
    else {auto ti=themes_.find(activeTheme_);if(ti!=themes_.end()){s=ti->second.base;for(auto&cls:n.classes){auto ci=ti->second.classes.find(cls);if(ci!=ti->second.classes.end())s=ci->second;}}}
    if(n.hasVisual)s=n.visual;if(!n.enabled&&n.hasDisabledVisual)s=n.disabledVisual;else if(n.pressed&&n.hasPressedVisual)s=n.pressedVisual;else if(n.focused&&n.hasFocusVisual)s=n.focusVisual;else if(n.hovered&&n.hasHoverVisual)s=n.hoverVisual;
    // Smooth state blending even without explicit per-node transition definitions.
    if(n.hoverProgress>0.0f&&n.enabled){GuiVisualStyle target=s;auto map=ResolveStyleMap(n);(void)map;/* resolved pseudo already contributes target */s.opacity=std::clamp(s.opacity,0.0f,1.0f);}
    return s;
}

GuiSize GuiFramework::MeasureNode(const GuiNode&n,GuiSize avail)const{
    auto style=ResolveVisual(n);float textW=std::min(avail.width,std::max(24.0f,(float)n.text.size()*style.fontSize*0.55f+24.0f));float textH=style.fontSize*style.lineHeight+14.0f;
    float defaultW=textW,defaultH=textH;
    switch(n.type){case GuiWidgetType::Button:case GuiWidgetType::ComboBox:case GuiWidgetType::Dropdown:case GuiWidgetType::TextInput:case GuiWidgetType::SearchBox:case GuiWidgetType::NumberInput:defaultH=34;break;case GuiWidgetType::IconButton:defaultW=defaultH=34;break;case GuiWidgetType::Toggle:defaultW=42;defaultH=24;break;case GuiWidgetType::Checkbox:case GuiWidgetType::Radio:defaultW=std::max(20.0f,textW);defaultH=24;break;case GuiWidgetType::Slider:case GuiWidgetType::RangeSlider:defaultW=160;defaultH=28;break;case GuiWidgetType::Progress:defaultW=160;defaultH=8;break;case GuiWidgetType::Spinner:defaultW=defaultH=24;break;case GuiWidgetType::TextArea:defaultW=240;defaultH=96;break;case GuiWidgetType::Badge:defaultH=22;break;case GuiWidgetType::Separator:defaultH=1;break;case GuiWidgetType::Viewport:defaultW=320;defaultH=220;break;default:break;}
    float w=ResolveDimension(n.layout.width,avail.width,defaultW+n.layout.padding.left+n.layout.padding.right);float h=ResolveDimension(n.layout.height,avail.height,defaultH+n.layout.padding.top+n.layout.padding.bottom);
    if(n.layout.aspectRatio>0){if(n.layout.width.mode!=GuiSizeMode::Content&&n.layout.height.mode==GuiSizeMode::Content)h=w/n.layout.aspectRatio;else if(n.layout.height.mode!=GuiSizeMode::Content&&n.layout.width.mode==GuiSizeMode::Content)w=h*n.layout.aspectRatio;}
    return{w,h};
}

void GuiFramework::LayoutNode(const std::string&id,GuiRectF available){
    auto it=nodes_.find(id);if(it==nodes_.end())return;GuiNode&n=it->second;if(!n.visible){n.computed={};return;}GuiSize measured=MeasureNode(n,{available.width,available.height});float x=available.x+n.layout.margin.left,y=available.y+n.layout.margin.top;
    if(n.layout.position!=GuiPositionMode::Flow){x=(n.layout.position==GuiPositionMode::Fixed?viewport_.safeArea.left:available.x)+n.layout.absoluteX;y=(n.layout.position==GuiPositionMode::Fixed?viewport_.safeArea.top:available.y)+n.layout.absoluteY;}
    float maxW=std::max(0.0f,available.width-n.layout.margin.left-n.layout.margin.right),maxH=std::max(0.0f,available.height-n.layout.margin.top-n.layout.margin.bottom);float w=std::min(measured.width,maxW),h=std::min(measured.height,maxH);if(n.layout.alignSelf==GuiAlign::Stretch&&n.layout.position==GuiPositionMode::Flow&&n.layout.width.mode==GuiSizeMode::Content)w=maxW;n.computed={x,y,w,h};
    GuiRectF content{x+n.layout.padding.left,y+n.layout.padding.top,std::max(0.0f,w-n.layout.padding.left-n.layout.padding.right),std::max(0.0f,h-n.layout.padding.top-n.layout.padding.bottom)};
    if(IsScrollable(n)&&Lower(n.data.Get("scrollbar_mode").AsString())=="classic"){float reserve=(float)styleSheet_.Token("--scrollbar-hover-size",VekValue(10.0)).AsNumber(10)+4.0f;content.width=std::max(0.0f,content.width-reserve);content.height=std::max(0.0f,content.height-reserve);}
    if(n.layout.overflow==GuiOverflow::ScrollX||n.layout.overflow==GuiOverflow::ScrollBoth)content.x-=std::max(0.0f,n.scrollX);if(n.layout.overflow==GuiOverflow::ScrollY||n.layout.overflow==GuiOverflow::ScrollBoth||n.type==GuiWidgetType::Scroll||n.type==GuiWidgetType::List||n.type==GuiWidgetType::Tree||n.type==GuiWidgetType::Table)content.y-=std::max(0.0f,n.scrollY);
    if(n.children.empty())return;std::vector<std::string>flow,absolute;for(auto&c:n.children){auto ci=nodes_.find(c);if(ci==nodes_.end()||!ci->second.visible)continue;(ci->second.layout.position==GuiPositionMode::Flow?flow:absolute).push_back(c);}for(auto&c:absolute)LayoutNode(c,content);
    float gap=n.layout.gap;if(n.layout.mode==GuiLayoutMode::Overlay||n.layout.mode==GuiLayoutMode::Absolute){for(auto&c:flow)LayoutNode(c,content);return;}
    if(n.layout.mode==GuiLayoutMode::Grid){int cols=std::max(1,n.layout.gridColumns);float cellW=std::max(0.0f,(content.width-gap*(cols-1))/cols);float rowY=content.y,rowH=0;for(std::size_t i=0;i<flow.size();++i){int col=(int)(i%cols);auto&cn=nodes_.at(flow[i]);auto ms=MeasureNode(cn,{cellW,content.height});if(col==0&&i>0){rowY+=rowH+gap;rowH=0;}rowH=std::max(rowH,ms.height);LayoutNode(flow[i],{content.x+col*(cellW+gap),rowY,cellW,ms.height});}return;}
    bool row=n.layout.mode==GuiLayoutMode::Row;float cursor=row?content.x:content.y,axisAvail=row?content.width:content.height;std::vector<float>sizes;float used=0;int fills=0;for(auto&c:flow){auto&cn=nodes_.at(c);auto ms=MeasureNode(cn,{content.width,content.height});float sz=row?ms.width:ms.height;bool fill=row?cn.layout.width.mode==GuiSizeMode::Fill:cn.layout.height.mode==GuiSizeMode::Fill;if(fill){sizes.push_back(-1);++fills;}else{sizes.push_back(sz);used+=sz;}}used+=gap*std::max<int>(0,(int)flow.size()-1);float remaining=std::max(0.0f,axisAvail-used),fillSize=fills?remaining/fills:0,total=used+(fills?remaining:0),extra=std::max(0.0f,axisAvail-total),localGap=gap;if(n.layout.justify==GuiJustify::Center)cursor+=extra*.5f;else if(n.layout.justify==GuiJustify::End)cursor+=extra;else if(n.layout.justify==GuiJustify::SpaceBetween&&flow.size()>1)localGap+=extra/(flow.size()-1);else if(n.layout.justify==GuiJustify::SpaceAround&&!flow.empty()){localGap+=extra/flow.size();cursor+=localGap*.5f;}
    for(std::size_t i=0;i<flow.size();++i){auto&cn=nodes_.at(flow[i]);float axis=sizes[i]<0?fillSize:sizes[i];auto ms=MeasureNode(cn,{content.width,content.height});GuiRectF a;if(row){float cross=cn.layout.alignSelf==GuiAlign::Stretch?content.height:ms.height,cy=content.y;if(cn.layout.alignSelf==GuiAlign::Center)cy+=std::max(0.0f,(content.height-cross)*.5f);else if(cn.layout.alignSelf==GuiAlign::End)cy+=std::max(0.0f,content.height-cross);a={cursor,cy,axis,cross};cursor+=axis+localGap;}else{float cross=cn.layout.alignSelf==GuiAlign::Stretch?content.width:ms.width,cx=content.x;if(cn.layout.alignSelf==GuiAlign::Center)cx+=std::max(0.0f,(content.width-cross)*.5f);else if(cn.layout.alignSelf==GuiAlign::End)cx+=std::max(0.0f,content.width-cross);a={cx,cursor,cross,axis};cursor+=axis+localGap;}LayoutNode(flow[i],a);}
}
void GuiFramework::Layout(){GuiRectF root{viewport_.safeArea.left,viewport_.safeArea.top,std::max(0.0f,viewport_.width-viewport_.safeArea.left-viewport_.safeArea.right),std::max(0.0f,viewport_.height-viewport_.safeArea.top-viewport_.safeArea.bottom)};for(auto&id:Roots())LayoutNode(id,root);layoutDirty_=false;}

static bool PointInsideAncestorClips(const GuiNode&node,GuiPoint p,const std::unordered_map<std::string,GuiNode>&nodes){std::string parent=node.parentId;while(!parent.empty()){auto it=nodes.find(parent);if(it==nodes.end())break;const auto&n=it->second;if((n.clipChildren||n.layout.overflow!=GuiOverflow::Visible||IsScrollable(n))&&!GuiContains(n.computed,p))return false;parent=n.parentId;}return true;}
std::string GuiFramework::HitTest(GuiPoint p)const{std::string best;int bestZ=std::numeric_limits<int>::min();float bestArea=std::numeric_limits<float>::max();for(auto&[id,n]:nodes_){if(!n.visible||!n.enabled||n.computed.width<=0||n.computed.height<=0||!GuiContains(n.computed,p)||!PointInsideAncestorClips(n,p,nodes_))continue;int z=ResolveVisual(n).zIndex;float area=n.computed.width*n.computed.height;if(z>bestZ||(z==bestZ&&area<bestArea)){best=id;bestZ=z;bestArea=area;}}return best;}
void GuiFramework::QueueEvent(GuiEvent e){if(events_.size()>=MaxEvents)events_.pop_front();events_.push_back(std::move(e));}
void GuiFramework::UpdateHover(const std::string&next,GuiPoint p){if(next==hoveredId_)return;if(auto*old=Find(hoveredId_)){old->hovered=false;QueueEvent({GuiEventType::PointerLeave,old->id,old->id,p});}hoveredId_=next;if(auto*n=Find(hoveredId_)){n->hovered=true;QueueEvent({GuiEventType::PointerEnter,n->id,n->id,p});}++revision_;}

static void UpdateSliderFromPointer(GuiNode&n,GuiPoint p,bool second=false){GuiRectF r=Inset(n.computed,10);double t=r.width>0?std::clamp((p.x-r.x)/r.width,0.0f,1.0f):0.0;double v=n.minValue+(n.maxValue-n.minValue)*t;if(n.step>0)v=std::round((v-n.minValue)/n.step)*n.step+n.minValue;v=std::clamp(v,n.minValue,n.maxValue);if(second)n.value2=v;else n.value=v;}

void GuiFramework::FeedInput(const GuiInputEvent&i){
    if(layoutDirty_)Layout();lastPointer_=i.pointer;std::string hit=HitTest(i.pointer);
    if(i.type==GuiInputType::PointerMove){lastFocusFromKeyboard_=false;UpdateHover(hit,i.pointer);if(!pressedId_.empty()){auto*n=Find(pressedId_);if(n){
            if(n->draggingScrollbarV||n->draggingScrollbarH){auto ext=MeasureContentExtents(*n,nodes_);ext.height=std::max(ext.height,(float)n->data.Get("content_height").AsNumber(0));ext.width=std::max(ext.width,(float)n->data.Get("content_width").AsNumber(0));float minThumb=(float)styleSheet_.Token("--scrollbar-min-thumb",VekValue(28.0)).AsNumber(28);if(n->draggingScrollbarV){auto m=ui::ComputeScrollbarMetrics(ext.height,n->computed.height,n->scrollOffsetStart,n->computed.height-8,minThumb);float travel=std::max(1.0f,m.trackLength-m.thumbLength);float delta=i.pointer.y-n->scrollDragStart;n->scrollY=std::clamp(n->scrollOffsetStart+delta/travel*m.maxScroll,0.0f,m.maxScroll);}else{auto m=ui::ComputeScrollbarMetrics(ext.width,n->computed.width,n->scrollOffsetStart,n->computed.width-8,minThumb);float travel=std::max(1.0f,m.trackLength-m.thumbLength);float delta=i.pointer.x-n->scrollDragStart;n->scrollX=std::clamp(n->scrollOffsetStart+delta/travel*m.maxScroll,0.0f,m.maxScroll);}n->scrollbarProgress=1.0f;MarkDirty();return;}
            float dx=i.pointer.x-n->pointerDown.x,dy=i.pointer.y-n->pointerDown.y;if(n->draggable&&!n->dragging&&dx*dx+dy*dy>=16.0f){n->dragging=true;dragId_=n->id;QueueEvent({GuiEventType::DragStart,n->id,n->id,i.pointer});}if(n->dragging)QueueEvent({GuiEventType::Drag,n->id,n->id,i.pointer});if(n->type==GuiWidgetType::Slider){UpdateSliderFromPointer(*n,i.pointer);GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.value=n->value;QueueEvent(ch);}else if(n->type==GuiWidgetType::RangeSlider){bool second=std::abs(NormalizedValue(*n,n->value2)-((i.pointer.x-n->computed.x)/std::max(1.0f,n->computed.width)))<std::abs(NormalizedValue(*n,n->value)-((i.pointer.x-n->computed.x)/std::max(1.0f,n->computed.width)));UpdateSliderFromPointer(*n,i.pointer,second);GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.value=n->value;VekMap d;d["value2"]=n->value2;ch.data=VekValue(d);QueueEvent(ch);}else if(n->type==GuiWidgetType::Timeline&&n->pressed){GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.value=std::clamp((double)((i.pointer.x-n->computed.x)/std::max(1.0f,n->computed.width)),0.0,1.0);VekMap d;d["interaction"]="drag_keyframe";ch.data=VekValue(d);QueueEvent(ch);}++revision_;}}if(!hit.empty())QueueEvent({GuiEventType::PointerMove,hit,hit,i.pointer});return;}
    if(i.type==GuiInputType::PointerDown){lastFocusFromKeyboard_=false;UpdateHover(hit,i.pointer);pressedId_=hit;if(auto*n=Find(hit)){n->pressed=true;n->pointerDown=i.pointer;if(IsScrollable(*n)){auto ext=MeasureContentExtents(*n,nodes_);ext.height=std::max(ext.height,(float)n->data.Get("content_height").AsNumber(0));ext.width=std::max(ext.width,(float)n->data.Get("content_width").AsNumber(0));float edge=14.0f;if(ext.height>n->computed.height+1&&i.pointer.x>=n->computed.x+n->computed.width-edge){n->draggingScrollbarV=true;n->scrollDragStart=i.pointer.y;n->scrollOffsetStart=n->scrollY;n->scrollbarProgress=1.0f;}else if(ext.width>n->computed.width+1&&i.pointer.y>=n->computed.y+n->computed.height-edge){n->draggingScrollbarH=true;n->scrollDragStart=i.pointer.x;n->scrollOffsetStart=n->scrollX;n->scrollbarProgress=1.0f;}}if(n->focusable){Focus(hit);n->focusVisible=false;}QueueEvent({GuiEventType::PointerDown,hit,hit,i.pointer});if(n->type==GuiWidgetType::Slider){UpdateSliderFromPointer(*n,i.pointer);GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.value=n->value;QueueEvent(ch);}++revision_;}return;}
    if(i.type==GuiInputType::PointerUp){lastFocusFromKeyboard_=false;UpdateHover(hit,i.pointer);std::string was=pressedId_;if(auto*n=Find(was)){n->pressed=false;n->draggingScrollbarV=false;n->draggingScrollbarH=false;QueueEvent({GuiEventType::PointerUp,was,was,i.pointer});if(n->dragging){QueueEvent({GuiEventType::DragEnd,was,was,i.pointer});n->dragging=false;dragId_.clear();}if(!was.empty()&&was==hit){if(n->type==GuiWidgetType::Checkbox||n->type==GuiWidgetType::Toggle||n->type==GuiWidgetType::Radio){n->checked=n->type==GuiWidgetType::Radio?true:!n->checked;GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.checked=n->checked;ch.value=n->checked?1.0:0.0;QueueEvent(ch);}if(n->type==GuiWidgetType::ComboBox||n->type==GuiWidgetType::Dropdown||n->type==GuiWidgetType::Menu){n->expanded=!n->expanded;QueueEvent({n->expanded?GuiEventType::Open:GuiEventType::Close,n->id,n->id,i.pointer});}if(n->type==GuiWidgetType::TreeItem){n->expanded=!n->expanded;QueueEvent({n->expanded?GuiEventType::Open:GuiEventType::Close,n->id,n->id,i.pointer});}if(n->type==GuiWidgetType::TabItem){n->selected=true;QueueEvent({GuiEventType::Select,n->id,n->id,i.pointer});}
                if(n->type==GuiWidgetType::Viewport&&n->data.Get("toolbar").AsBool(true)){GuiRectF tb{n->computed.x+n->computed.width-126,n->computed.y+10,116,32};if(GuiContains(tb,i.pointer)){int index=std::clamp((int)((i.pointer.x-(tb.x+4))/34),0,2);const char*actions[]={"reset_view","toggle_wireframe","zoom"};GuiEvent a{GuiEventType::Select,n->id,n->id,i.pointer};a.text=actions[index];QueueEvent(a);}}
                QueueEvent({GuiEventType::Click,was,was,i.pointer});}if(!hit.empty()&&hit!=was){auto*d=Find(hit);if(d&&d->droppable){d->dropTarget=false;GuiEvent drop{GuiEventType::Drop,hit,hit,i.pointer};drop.text=was;QueueEvent(drop);}}}pressedId_.clear();++revision_;return;}
    if(i.type==GuiInputType::Scroll){std::string target=hit;while(!target.empty()){auto*n=Find(target);if(!n)break;if(IsScrollable(*n)){n->scrollX=std::max(0.0f,n->scrollX+i.scrollX);n->scrollY=std::max(0.0f,n->scrollY+i.scrollY);n->scrollbarProgress=1.0f;GuiEvent e{GuiEventType::Scroll,target,target,i.pointer};e.value=i.scrollY;QueueEvent(e);MarkDirty();return;}target=n->parentId;}return;}
    if(i.type==GuiInputType::KeyDown){lastFocusFromKeyboard_=true;if(i.key==9){FocusNext(i.shift);if(auto*n=Find(focusedId_))n->focusVisible=true;return;}if(!focusedId_.empty()){auto*n=Find(focusedId_);if(n)n->focusVisible=true;GuiEvent e{GuiEventType::KeyDown,focusedId_,focusedId_,i.pointer};e.key=i.key;QueueEvent(e);if(i.key==13||i.key==32){if(n&&(n->type==GuiWidgetType::Button||n->type==GuiWidgetType::IconButton||n->type==GuiWidgetType::MenuItem||n->type==GuiWidgetType::TabItem))QueueEvent({GuiEventType::Click,n->id,n->id,i.pointer});if(i.key==13)QueueEvent({GuiEventType::Submit,focusedId_,focusedId_,i.pointer});}if(i.key==8&&n&&IsTextInputType(n->type)&&!n->text.empty()){n->text.pop_back();GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.text=n->text;QueueEvent(ch);++revision_;}}return;}
    if(i.type==GuiInputType::KeyUp){if(!focusedId_.empty()){GuiEvent e{GuiEventType::KeyUp,focusedId_,focusedId_,i.pointer};e.key=i.key;QueueEvent(e);}return;}
    if(i.type==GuiInputType::TextInput&&!focusedId_.empty()){auto*n=Find(focusedId_);if(n&&IsTextInputType(n->type)){n->text+=i.text;GuiEvent e{GuiEventType::TextInput,n->id,n->id,i.pointer};e.text=i.text;QueueEvent(e);GuiEvent ch{GuiEventType::Change,n->id,n->id,i.pointer};ch.text=n->text;QueueEvent(ch);++revision_;}}
}

bool GuiFramework::PollEvent(GuiEvent&e){if(events_.empty())return false;e=std::move(events_.front());events_.pop_front();return true;}
std::vector<GuiEvent>GuiFramework::DrainEvents(std::size_t max){std::vector<GuiEvent>out;max=std::min(max,events_.size());out.reserve(max);while(max--){out.push_back(std::move(events_.front()));events_.pop_front();}return out;}
std::vector<std::string>GuiFramework::FocusOrder()const{std::vector<const GuiNode*>v;for(auto&[id,n]:nodes_)if(n.visible&&n.enabled&&n.focusable&&!n.accessibility.hidden)v.push_back(&n);std::sort(v.begin(),v.end(),[](auto*a,auto*b){if(a->accessibility.navigationOrder!=b->accessibility.navigationOrder)return a->accessibility.navigationOrder<b->accessibility.navigationOrder;if(a->computed.y!=b->computed.y)return a->computed.y<b->computed.y;if(a->computed.x!=b->computed.x)return a->computed.x<b->computed.x;return a->id<b->id;});std::vector<std::string>r;for(auto*n:v)r.push_back(n->id);return r;}
bool GuiFramework::Focus(const std::string&id){auto*n=Find(id);if(!n||!n->visible||!n->enabled||!n->focusable)return false;if(focusedId_==id){n->focusVisible=lastFocusFromKeyboard_;return true;}if(auto*old=Find(focusedId_)){old->focused=false;old->focusVisible=false;QueueEvent({GuiEventType::Blur,old->id,old->id,lastPointer_});}focusedId_=id;n->focused=true;n->focusVisible=lastFocusFromKeyboard_;QueueEvent({GuiEventType::Focus,id,id,lastPointer_});++revision_;return true;}
bool GuiFramework::FocusNext(bool reverse){if(layoutDirty_)Layout();auto order=FocusOrder();if(order.empty())return false;auto it=std::find(order.begin(),order.end(),focusedId_);std::size_t idx=0;if(it!=order.end()){auto cur=(std::size_t)std::distance(order.begin(),it);idx=reverse?(cur+order.size()-1)%order.size():(cur+1)%order.size();}else idx=reverse?order.size()-1:0;lastFocusFromKeyboard_=true;return Focus(order[idx]);}
void GuiFramework::ClearFocus(){if(auto*n=Find(focusedId_)){n->focused=false;n->focusVisible=false;QueueEvent({GuiEventType::Blur,n->id,n->id,lastPointer_});}focusedId_.clear();++revision_;}

bool GuiFramework::StartAnimation(const GuiAnimation&a,std::string*error){if(!Find(a.nodeId)){if(error)*error="animation node not found";return false;}if(a.property.empty()){if(error)*error="animation property missing";return false;}if(animations_.size()>=MaxAnimations){if(error)*error="animation limit reached";return false;}GuiAnimation x=a;x.duration=std::clamp(std::isfinite(x.duration)?x.duration:.2,0.001,3600.0);x.elapsed=0;animations_.push_back(x);return true;}
bool GuiFramework::StopAnimations(const std::string&id,const std::string&property){auto old=animations_.size();animations_.erase(std::remove_if(animations_.begin(),animations_.end(),[&](const GuiAnimation&a){return a.nodeId==id&&(property.empty()||a.property==property);}),animations_.end());return old!=animations_.size();}
void GuiFramework::Step(double dt){if(!std::isfinite(dt)||dt<=0)return;dt=std::min(dt,.25);float fdt=(float)dt;auto approach=[&](float&v,float target,float duration){if(duration<=0){v=target;return;}float k=1-std::exp(-8.0f*fdt/std::max(.01f,duration));v+=(target-v)*k;};for(auto&[id,n]:nodes_){auto st=ResolveVisual(n);approach(n.hoverProgress,n.hovered?1.f:0.f,st.transitionDuration);approach(n.pressProgress,n.pressed?1.f:0.f,st.transitionDuration*.7f);approach(n.focusProgress,n.focusVisible?1.f:0.f,st.transitionDuration);approach(n.openProgress,n.expanded?1.f:0.f,st.transitionDuration);approach(n.checkProgress,(n.checked||n.selected)?1.f:0.f,st.transitionDuration);approach(n.scrollbarProgress,(n.hovered&&IsScrollable(n))?1.f:0.f,.18f);}
    for(std::size_t i=0;i<animations_.size();){auto&a=animations_[i];a.elapsed+=dt;float t=(float)std::clamp(a.elapsed/a.duration,0.0,1.0),e=EaseValue(a.ease,t);double val=a.from+(a.to-a.from)*e;auto*n=Find(a.nodeId);if(n){if(a.property=="opacity")n->visual.opacity=Clamp01((float)val);else if(a.property=="x")n->layout.absoluteX=(float)val;else if(a.property=="y")n->layout.absoluteY=(float)val;else if(a.property=="width"){n->layout.width.mode=GuiSizeMode::Fixed;n->layout.width.value=(float)val;}else if(a.property=="height"){n->layout.height.mode=GuiSizeMode::Fixed;n->layout.height.value=(float)val;}else if(a.property=="value")n->value=std::clamp(val,n->minValue,n->maxValue);else if(a.property=="scroll_x")n->scrollX=(float)val;else if(a.property=="scroll_y")n->scrollY=(float)val;else if(a.property=="radius")n->visual.radius=std::max(0.0f,(float)val);}bool done=t>=1;if(done&&a.loop){a.elapsed=0;if(a.pingPong){std::swap(a.from,a.to);a.reverse=!a.reverse;}++i;}else if(done)animations_.erase(animations_.begin()+i);else ++i;}MarkDirty();}

void GuiFramework::BuildScrollbarCommands(const GuiNode&n,const GuiVisualStyle&style,std::vector<GuiDrawCommand>&out,int layer)const{
    if(!IsScrollable(n))return;auto ext=MeasureContentExtents(n,nodes_);float contentH=std::max(ext.height,(float)n.data.Get("content_height").AsNumber(0));float contentW=std::max(ext.width,(float)n.data.Get("content_width").AsNumber(0));if(contentH<=n.computed.height+1&&contentW<=n.computed.width+1)return;
    float base=(float)styleSheet_.Token("--scrollbar-size",VekValue(7.0)).AsNumber(7),hover=(float)styleSheet_.Token("--scrollbar-hover-size",VekValue(10.0)).AsNumber(10),minThumb=(float)styleSheet_.Token("--scrollbar-min-thumb",VekValue(28.0)).AsNumber(28);float thickness=base+(hover-base)*n.scrollbarProgress;
    GuiColor track=ColorFromValue(styleSheet_.Token("--scrollbar-track",VekValue("#00000000")),{0,0,0,0});GuiColor thumb=ColorFromValue(styleSheet_.Token(n.hovered?"--scrollbar-thumb-hover":"--scrollbar-thumb",VekValue("#78839188")),{.45f,.5f,.58f,.5f});
    if(contentH>n.computed.height+1){auto m=ui::ComputeScrollbarMetrics(contentH,n.computed.height,n.scrollY,n.computed.height-8,minThumb);GuiRectF tr{n.computed.x+n.computed.width-thickness-3,n.computed.y+4,thickness,m.trackLength};auto c=Cmd(GuiDrawType::Box,n,"scrollbar.v.track",tr,style,layer+8);c.color=track;c.style.background=track;c.style.radius=thickness*.5f;out.push_back(c);GuiRectF th{tr.x,tr.y+m.thumbStart,thickness,m.thumbLength};c=Cmd(GuiDrawType::Box,n,"scrollbar.v.thumb",th,style,layer+9);c.color=thumb;c.style.background=thumb;c.style.radius=thickness*.5f;out.push_back(c);auto sh=ui::ComputeScrollShadowMetrics(contentH,n.computed.height,n.scrollY);if(sh.leadingOpacity>0){c=Cmd(GuiDrawType::Gradient,n,"scroll.shadow.top",{n.computed.x,n.computed.y,n.computed.width,18},style,layer+7);c.color=WithAlpha(style.shadowColor,.22f*sh.leadingOpacity);c.value=-1;out.push_back(c);}if(sh.trailingOpacity>0){c=Cmd(GuiDrawType::Gradient,n,"scroll.shadow.bottom",{n.computed.x,n.computed.y+n.computed.height-18,n.computed.width,18},style,layer+7);c.color=WithAlpha(style.shadowColor,.22f*sh.trailingOpacity);c.value=1;out.push_back(c);}}
    if(contentW>n.computed.width+1){auto m=ui::ComputeScrollbarMetrics(contentW,n.computed.width,n.scrollX,n.computed.width-8,minThumb);GuiRectF tr{n.computed.x+4,n.computed.y+n.computed.height-thickness-3,m.trackLength,thickness};auto c=Cmd(GuiDrawType::Box,n,"scrollbar.h.track",tr,style,layer+8);c.color=track;c.style.background=track;c.style.radius=thickness*.5f;out.push_back(c);GuiRectF th{tr.x+m.thumbStart,tr.y,m.thumbLength,thickness};c=Cmd(GuiDrawType::Box,n,"scrollbar.h.thumb",th,style,layer+9);c.color=thumb;c.style.background=thumb;c.style.radius=thickness*.5f;out.push_back(c);}
}

void GuiFramework::BuildWidgetDrawCommands(const GuiNode&n,const GuiVisualStyle&raw,std::vector<GuiDrawCommand>&out,int layer)const{
    GuiVisualStyle style=raw;GuiRectF r=ScaleRect(n.computed,style.scale,style.translateX,style.translateY);style.opacity*=n.enabled?1.0f:.55f;
    auto addBox=[&](std::string part,GuiRectF rr,GuiVisualStyle st,int l=0){auto c=Cmd(GuiDrawType::Box,n,part,rr,st,layer+l);out.push_back(c);};
    auto addText=[&](std::string part,GuiRectF rr,std::string text,GuiVisualStyle st,int l=1){auto c=Cmd(GuiDrawType::Text,n,part,rr,st,layer+l);c.text=std::move(text);out.push_back(c);};
    auto addLine=[&](std::string part,GuiPoint a,GuiPoint b,GuiColor color,float thick,int l=1){auto c=Cmd(GuiDrawType::Line,n,part,{},style,layer+l);c.from=a;c.to=b;c.color=color;c.thickness=thick;out.push_back(c);};
    auto addCircle=[&](std::string part,GuiRectF rr,GuiColor color,int l=1){auto c=Cmd(GuiDrawType::Circle,n,part,rr,style,layer+l);c.color=color;out.push_back(c);};
    if(style.shadowBlur>0&&style.shadowColor.a>0){auto c=Cmd(GuiDrawType::Shadow,n,"shadow",r,style,layer-1);c.color=style.shadowColor;c.value=style.shadowBlur;out.push_back(c);}
    if(n.focusVisible&&style.focusRingWidth>0){auto fs=style;fs.background={0,0,0,0};fs.border=style.focusRingColor;fs.borderWidth=style.focusRingWidth;addBox("focus-ring",{r.x-style.focusRingWidth*2,r.y-style.focusRingWidth*2,r.width+style.focusRingWidth*4,r.height+style.focusRingWidth*4},fs,-1);}

    switch(n.type){
    case GuiWidgetType::Root:case GuiWidgetType::Window:case GuiWidgetType::Modal:case GuiWidgetType::Panel:case GuiWidgetType::Card:case GuiWidgetType::DockSpace:case GuiWidgetType::SplitPane:case GuiWidgetType::TabView:case GuiWidgetType::MenuBar:case GuiWidgetType::Menu:case GuiWidgetType::ToolBar:case GuiWidgetType::StatusBar:case GuiWidgetType::List:case GuiWidgetType::Tree:case GuiWidgetType::Table:case GuiWidgetType::Scroll:case GuiWidgetType::PropertyGrid:case GuiWidgetType::Canvas:
        addBox("surface",r,style);
        if(n.type==GuiWidgetType::Table){
            float hh=(float)n.data.Get("header_height").AsNumber(32);
            if(n.data.Get("sticky_header").AsBool(true)&&hh>0){auto hs=style;hs.background=ColorFromValue(styleSheet_.Token("--surface-raised",VekValue("#1c212a")),style.background);addBox("table.sticky-header",{r.x,r.y,r.width,std::min(hh,r.height)},hs,5);auto c=Cmd(GuiDrawType::Custom,n,"table.columns",{r.x,r.y,r.width,std::min(hh,r.height)},style,layer+6);c.data=n.data;out.push_back(c);}
        }
        if(n.type==GuiWidgetType::PropertyGrid){auto c=Cmd(GuiDrawType::Custom,n,"property-grid.rows",Inset(r,4),style,layer+2);c.data=n.data;out.push_back(c);}
        if(n.type==GuiWidgetType::DockSpace||n.type==GuiWidgetType::SplitPane){auto c=Cmd(GuiDrawType::Custom,n,"dock.handles",r,style,layer+4);c.data=n.data;out.push_back(c);}
        break;
    case GuiWidgetType::Button:case GuiWidgetType::IconButton:case GuiWidgetType::MenuItem:case GuiWidgetType::ListItem:case GuiWidgetType::TableRow:case GuiWidgetType::TableCell:case GuiWidgetType::Badge:case GuiWidgetType::Keybind:
        if(n.type==GuiWidgetType::TableRow&&n.data.Get("row_index").AsNumber(-1)>=0&&((int)n.data.Get("row_index").AsNumber()%2)==1){auto zebra=style;zebra.background=ColorFromValue(styleSheet_.Token("--table-zebra",VekValue("#12161c")),zebra.background);addBox("row.zebra",r,zebra);}else addBox("surface",r,style);
        if(!style.icon.empty()||!n.data.Get("icon").AsString().empty()){auto c=Cmd(GuiDrawType::Icon,n,"icon",{r.x+10,r.y+(r.height-style.iconSize)*.5f,style.iconSize,style.iconSize},style,layer+1);c.icon=!n.data.Get("icon").AsString().empty()?n.data.Get("icon").AsString():style.icon;c.color=style.foreground;out.push_back(c);}if(!n.text.empty())addText("label",r,n.text,style,2);break;
    case GuiWidgetType::Toggle:{addBox("toggle.track",r,style);float d=std::max(10.0f,r.height-6),x=r.x+3+(r.width-d-6)*n.checkProgress;addCircle("toggle.thumb",{x,r.y+(r.height-d)*.5f,d,d},n.checked?GuiColor{1,1,1,1}:style.foreground,2);break;}
    case GuiWidgetType::Checkbox:{GuiRectF box{r.x,r.y+(r.height-18)*.5f,18,18};addBox("checkbox.box",box,style);if(n.checked){auto c=Cmd(GuiDrawType::Custom,n,"checkbox.check",box,style,layer+2);c.color={1,1,1,1};out.push_back(c);}if(!n.text.empty())addText("label",{r.x+26,r.y,std::max(0.0f,r.width-26),r.height},n.text,style,2);break;}
    case GuiWidgetType::Radio:{GuiRectF box{r.x,r.y+(r.height-18)*.5f,18,18};addCircle("radio.outer",box,style.border);if(n.checked)addCircle("radio.dot",Inset(box,5),style.accent,2);if(!n.text.empty())addText("label",{r.x+26,r.y,std::max(0.0f,r.width-26),r.height},n.text,style,2);break;}
    case GuiWidgetType::Slider:case GuiWidgetType::RangeSlider:{GuiRectF track{r.x+10,r.y+r.height*.5f-2,std::max(0.0f,r.width-20),4};auto ts=style;ts.background=style.background;ts.radius=2;addBox("slider.track",track,ts);double a=NormalizedValue(n,n.value),b=n.type==GuiWidgetType::RangeSlider?NormalizedValue(n,n.value2):a;if(b<a)std::swap(a,b);GuiRectF fill{track.x+(float)(track.width*(n.type==GuiWidgetType::RangeSlider?a:0)),track.y,(float)(track.width*(n.type==GuiWidgetType::RangeSlider?b-a:a)),track.height};ts.background=style.accent;addBox("slider.fill",fill,ts,1);float thumb=14;addCircle("slider.thumb",{track.x+(float)(track.width*NormalizedValue(n,n.value))-thumb*.5f,r.y+r.height*.5f-thumb*.5f,thumb,thumb},style.accent,3);if(n.type==GuiWidgetType::RangeSlider)addCircle("slider.thumb2",{track.x+(float)(track.width*NormalizedValue(n,n.value2))-thumb*.5f,r.y+r.height*.5f-thumb*.5f,thumb,thumb},style.accent,3);int ticks=(int)n.data.Get("ticks").AsNumber(0);for(int i=0;i<ticks;i++){float tx=track.x+track.width*(ticks<=1?0.0f:(float)i/(ticks-1));addLine("slider.tick",{tx,track.y+7},{tx,track.y+10},WithAlpha(style.foreground,.45f),1,1);}break;}
    case GuiWidgetType::Progress:{addBox("progress.track",r,style);double t=NormalizedValue(n,n.value);auto fs=style;fs.background=style.accent;addBox("progress.fill",{r.x,r.y,(float)(r.width*t),r.height},fs,1);if(n.data.Get("indeterminate").AsBool(false)){auto c=Cmd(GuiDrawType::Gradient,n,"progress.indeterminate",r,fs,layer+2);c.value=(float)n.openProgress;out.push_back(c);}break;}
    case GuiWidgetType::Spinner:{auto c=Cmd(GuiDrawType::Custom,n,"spinner.arc",r,style,layer+1);c.color=style.accent;c.thickness=std::max(2.0f,r.width*.1f);c.value=(float)n.openProgress;out.push_back(c);break;}
    case GuiWidgetType::TextInput:case GuiWidgetType::TextArea:case GuiWidgetType::SearchBox:case GuiWidgetType::NumberInput:case GuiWidgetType::ComboBox:case GuiWidgetType::Dropdown:{addBox("input.surface",r,style);float left=12;if(n.type==GuiWidgetType::SearchBox){auto c=Cmd(GuiDrawType::Icon,n,"search.icon",{r.x+10,r.y+(r.height-16)*.5f,16,16},style,layer+1);c.icon="search";c.color=style.foreground;out.push_back(c);left=34;}if(!n.text.empty())addText("input.text",{r.x+left,r.y,std::max(0.0f,r.width-left-12),r.height},n.text,style,2);else{auto placeholder=n.data.Get("placeholder").AsString();if(!placeholder.empty()){auto ps=style;ps.foreground=WithAlpha(style.foreground,.52f);addText("input.placeholder",{r.x+left,r.y,std::max(0.0f,r.width-left-12),r.height},placeholder,ps,2);}}if(n.type==GuiWidgetType::ComboBox||n.type==GuiWidgetType::Dropdown){auto c=Cmd(GuiDrawType::Icon,n,"dropdown.chevron",{r.x+r.width-24,r.y+(r.height-14)*.5f,14,14},style,layer+2);c.icon=n.expanded?"chevron-up":"chevron-down";c.color=style.foreground;out.push_back(c);}if(n.invalid||n.warning||n.success){auto vs=style;vs.background=n.invalid?GuiColor{.94f,.26f,.3f,1}:n.warning?GuiColor{.9f,.62f,.18f,1}:GuiColor{.2f,.72f,.46f,1};addBox("input.validation",{r.x,r.y+r.height-2,r.width,2},vs,3);}break;}
    case GuiWidgetType::TabItem:{addBox("tab.surface",r,style);if(!n.text.empty())addText("tab.label",r,n.text,style,2);if(n.selected){auto is=style;is.background=style.accent;is.radius=2;addBox("tab.indicator",{r.x+8,r.y+r.height-3,std::max(0.0f,r.width-16),3},is,3);}break;}
    case GuiWidgetType::TreeItem:{addBox("tree.row",r,style);int depth=(int)n.data.Get("depth").AsNumber(0);for(int d=0;d<depth;d++){float x=r.x+10+d*16;addLine("tree.indent",{x,r.y},{x,r.y+r.height},WithAlpha(style.border,.55f),1);}auto c=Cmd(GuiDrawType::Icon,n,"tree.chevron",{r.x+8+depth*16,r.y+(r.height-14)*.5f,14,14},style,layer+2);c.icon=n.expanded?"chevron-down":"chevron-right";c.color=style.foreground;out.push_back(c);if(!n.text.empty())addText("tree.label",{r.x+28+depth*16,r.y,std::max(0.0f,r.width-30-depth*16),r.height},n.text,style,2);break;}
    case GuiWidgetType::Label:case GuiWidgetType::RichText:{if(!n.text.empty())addText(n.type==GuiWidgetType::RichText?"rich-text":"label",r,n.text,style,1);break;}
    case GuiWidgetType::Separator:{auto ss=style;ss.background=style.border;addBox("separator",r,ss);break;}
    case GuiWidgetType::Image:{auto c=Cmd(GuiDrawType::Image,n,"image",r,style,layer);c.image=n.image;out.push_back(c);break;}
    case GuiWidgetType::Tooltip:case GuiWidgetType::ContextMenu:case GuiWidgetType::Popup:case GuiWidgetType::Toast:{addBox("overlay.surface",r,style);if(style.backdropBlur>0){auto c=Cmd(GuiDrawType::Custom,n,"backdrop.blur",r,style,layer-1);c.value=style.backdropBlur;out.push_back(c);}if(!n.text.empty())addText("overlay.text",r,n.text,style,2);break;}
    case GuiWidgetType::ColorPicker:{addBox("picker.surface",r,style);auto c=Cmd(GuiDrawType::Gradient,n,"picker.sv",Inset(r,8),style,layer+1);c.data=n.data;out.push_back(c);break;}
    case GuiWidgetType::Viewport:{addBox("viewport.frame",r,style);auto bg=Cmd(GuiDrawType::Gradient,n,"viewport.backdrop",Inset(r,std::max(1.0f,style.borderWidth)),style,layer+1);bg.value=-1;bg.data=n.data;out.push_back(bg);auto content=Cmd(GuiDrawType::Custom,n,"viewport.content",Inset(r,2),style,layer+2);content.data=n.data;out.push_back(content);std::string state=n.data.Get("state").AsString();if(state=="loading"){auto c=Cmd(GuiDrawType::Custom,n,"viewport.loading",Inset(r,20),style,layer+4);c.color=style.accent;out.push_back(c);}else if(state=="empty"){auto es=style;es.foreground=WithAlpha(style.foreground,.58f);{auto emptyText=n.data.Get("empty_text").AsString();if(emptyText.empty())emptyText="No preview";addText("viewport.empty",Inset(r,24),emptyText,es,4);}}if(n.data.Get("toolbar").AsBool(true)){GuiRectF tb{r.x+r.width-126,r.y+10,116,32};auto ts=style;ts.background=WithAlpha(style.background,.82f);ts.radius=8;addBox("viewport.toolbar",tb,ts,5);const char*icons[]={"reset-view","wireframe","zoom"};for(int i=0;i<3;i++){auto c=Cmd(GuiDrawType::Icon,n,std::string("viewport.toolbar.")+icons[i],{tb.x+8+i*34,tb.y+8,16,16},style,layer+6);c.icon=icons[i];c.color=style.foreground;out.push_back(c);}}auto giz=Cmd(GuiDrawType::Custom,n,"viewport.corner-gizmo",{r.x+r.width-48,r.y+r.height-48,38,38},style,layer+5);giz.data=n.data;out.push_back(giz);break;}
    case GuiWidgetType::Graph:{addBox("graph.surface",r,style);for(int i=1;i<6;i++){float x=r.x+r.width*i/6.0f;addLine("graph.grid.v",{x,r.y},{x,r.y+r.height},WithAlpha(style.border,.42f),1);float y=r.y+r.height*i/6.0f;addLine("graph.grid.h",{r.x,y},{r.x+r.width,y},WithAlpha(style.border,.42f),1);}auto c=Cmd(GuiDrawType::Custom,n,"graph.curves",Inset(r,8),style,layer+2);c.data=n.data;c.color=style.accent;out.push_back(c);if(n.hovered){addLine("graph.crosshair.v",{lastPointer_.x,r.y},{lastPointer_.x,r.y+r.height},WithAlpha(style.foreground,.4f),1,3);addLine("graph.crosshair.h",{r.x,lastPointer_.y},{r.x+r.width,lastPointer_.y},WithAlpha(style.foreground,.4f),1,3);}break;}
    case GuiWidgetType::Timeline:{addBox("timeline.surface",r,style);for(int i=0;i<=10;i++){float x=r.x+r.width*i/10.0f;addLine("timeline.grid",{x,r.y},{x,r.y+r.height},WithAlpha(style.border,i%5==0?.6f:.3f),i%5==0?1.5f:1.0f);}auto c=Cmd(GuiDrawType::Custom,n,"timeline.keyframes",Inset(r,8),style,layer+2);c.data=n.data;c.color=style.accent;out.push_back(c);break;}
    case GuiWidgetType::Spacer:break;
    }
    BuildScrollbarCommands(n,style,out,layer);
}

void GuiFramework::BuildDrawNode(const std::string&id,std::vector<GuiDrawCommand>&out,int inherited)const{auto it=nodes_.find(id);if(it==nodes_.end())return;const auto&n=it->second;if(!n.visible||n.computed.width<=0||n.computed.height<=0)return;auto style=ResolveVisual(n);int layer=inherited+style.zIndex;bool clips=n.clipChildren||n.layout.overflow!=GuiOverflow::Visible||IsScrollable(n);if(clips){auto c=Cmd(GuiDrawType::ClipPush,n,"clip",n.computed,style,layer);c.clip=true;out.push_back(c);}BuildWidgetDrawCommands(n,style,out,layer);for(auto&c:n.children)BuildDrawNode(c,out,layer);if(clips){auto c=Cmd(GuiDrawType::ClipPop,n,"clip",n.computed,style,layer+20);c.clip=true;out.push_back(c);}}
std::vector<GuiDrawCommand>GuiFramework::BuildDrawList()const{auto*self=const_cast<GuiFramework*>(this);if(layoutDirty_)self->Layout();std::vector<GuiDrawCommand>out;for(auto&id:Roots())BuildDrawNode(id,out,0);std::stable_sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.layer<b.layer;});return out;}
GuiFrameStats GuiFramework::Stats()const{GuiFrameStats s;s.revision=revision_;s.nodeCount=nodes_.size();for(auto&[id,n]:nodes_)if(n.visible)++s.visibleNodeCount;auto draw=BuildDrawList();s.drawCommandCount=draw.size();for(auto&d:draw)if(d.type!=GuiDrawType::Box&&d.type!=GuiDrawType::Text&&d.type!=GuiDrawType::Image&&d.type!=GuiDrawType::ClipPush&&d.type!=GuiDrawType::ClipPop)++s.modernPrimitiveCount;s.queuedEventCount=events_.size();s.activeAnimationCount=animations_.size();s.focusedId=focusedId_;s.hoveredId=hoveredId_;return s;}
VekValue GuiFramework::Snapshot()const{auto*self=const_cast<GuiFramework*>(this);if(layoutDirty_)self->Layout();VekArray arr;arr.reserve(nodes_.size());std::vector<std::string>ids;for(auto&[id,n]:nodes_)ids.push_back(id);std::sort(ids.begin(),ids.end());for(auto&id:ids){auto&n=nodes_.at(id);VekMap m;m["id"]=n.id;m["type"]=GuiWidgetTypeName(n.type);m["parent"]=n.parentId;m["text"]=n.text;m["rect"]=RectToValue(n.computed);m["visible"]=n.visible;m["enabled"]=n.enabled;m["focused"]=n.focused;m["focus_visible"]=n.focusVisible;m["hovered"]=n.hovered;m["checked"]=n.checked;m["selected"]=n.selected;m["expanded"]=n.expanded;m["value"]=n.value;m["value2"]=n.value2;m["scroll_x"]=n.scrollX;m["scroll_y"]=n.scrollY;m["data"]=n.data;arr.emplace_back(m);}VekMap root;root["api_version"]=ApiVersion;root["theme"]=activeTheme_;root["width"]=viewport_.width;root["height"]=viewport_.height;root["dpi_scale"]=viewport_.dpiScale;root["modern_style"]=modernStyleEnabled_;root["nodes"]=VekValue(arr);return VekValue(root);}

void GuiFramework::RegisterNatives(VekScriptEngine&e){
    e.RegisterNative("ui_version",[](const std::vector<VekValue>&){return VekValue(ApiVersion);});e.RegisterNative("ui_create",[this](const std::vector<VekValue>&a){std::string err;return VekValue(!a.empty()&&CreateValue(a[0],&err));});e.RegisterNative("ui_patch",[this](const std::vector<VekValue>&a){std::string err;return VekValue(a.size()>=2&&Patch(a[0].AsString(),a[1],&err));});e.RegisterNative("ui_remove",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Remove(a[0].AsString(),a.size()<2||a[1].AsBool(true)));});e.RegisterNative("ui_clear",[this](const std::vector<VekValue>&){Clear();return VekValue();});e.RegisterNative("ui_count",[this](const std::vector<VekValue>&){return VekValue((double)Size());});e.RegisterNative("ui_exists",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Find(a[0].AsString())!=nullptr);});
    e.RegisterNative("ui_set_viewport",[this](const std::vector<VekValue>&a){if(a.size()>=2){GuiViewport v=viewport_;v.width=(float)a[0].AsNumber(v.width);v.height=(float)a[1].AsNumber(v.height);if(a.size()>2)v.dpiScale=(float)a[2].AsNumber(v.dpiScale);SetViewport(v);}return VekValue();});e.RegisterNative("ui_layout",[this](const std::vector<VekValue>&){Layout();return VekValue();});e.RegisterNative("ui_rect",[this](const std::vector<VekValue>&a){if(a.empty())return VekValue();if(layoutDirty_)Layout();auto*n=Find(a[0].AsString());return n?RectToValue(n->computed):VekValue();});e.RegisterNative("ui_hit_test",[this](const std::vector<VekValue>&a){if(a.size()<2)return VekValue("");if(layoutDirty_)Layout();return VekValue(HitTest({(float)a[0].AsNumber(),(float)a[1].AsNumber()}));});
    e.RegisterNative("ui_focus",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Focus(a[0].AsString()));});e.RegisterNative("ui_focus_next",[this](const std::vector<VekValue>&a){return VekValue(FocusNext(!a.empty()&&a[0].AsBool()));});e.RegisterNative("ui_focused",[this](const std::vector<VekValue>&){return VekValue(focusedId_);});
    e.RegisterNative("ui_feed_pointer",[this](const std::vector<VekValue>&a){if(a.size()>=3){GuiInputEvent i;auto t=Lower(a[0].AsString());i.type=t=="down"?GuiInputType::PointerDown:t=="up"?GuiInputType::PointerUp:GuiInputType::PointerMove;i.pointer={(float)a[1].AsNumber(),(float)a[2].AsNumber()};if(a.size()>3)i.button=(int)a[3].AsNumber();FeedInput(i);}return VekValue();});e.RegisterNative("ui_feed_scroll",[this](const std::vector<VekValue>&a){if(a.size()>=4){GuiInputEvent i;i.type=GuiInputType::Scroll;i.pointer={(float)a[0].AsNumber(),(float)a[1].AsNumber()};i.scrollX=(float)a[2].AsNumber();i.scrollY=(float)a[3].AsNumber();FeedInput(i);}return VekValue();});e.RegisterNative("ui_feed_key",[this](const std::vector<VekValue>&a){if(a.size()>=2){GuiInputEvent i;i.type=Lower(a[0].AsString())=="up"?GuiInputType::KeyUp:GuiInputType::KeyDown;i.key=(int)a[1].AsNumber();if(a.size()>2)i.shift=a[2].AsBool();FeedInput(i);}return VekValue();});e.RegisterNative("ui_feed_text",[this](const std::vector<VekValue>&a){if(!a.empty()){GuiInputEvent i;i.type=GuiInputType::TextInput;i.text=a[0].AsString();FeedInput(i);}return VekValue();});e.RegisterNative("ui_next_event",[this](const std::vector<VekValue>&){GuiEvent ev;return PollEvent(ev)?EventToValue(ev):VekValue();});
    e.RegisterNative("ui_define_theme",[this](const std::vector<VekValue>&a){std::string err;return VekValue(!a.empty()&&DefineThemeValue(a[0],&err));});e.RegisterNative("ui_set_theme",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&SetTheme(a[0].AsString()));});e.RegisterNative("ui_theme",[this](const std::vector<VekValue>&){return VekValue(activeTheme_);});e.RegisterNative("ui_load_styles",[this](const std::vector<VekValue>&a){return VekValue((double)(a.empty()?0:LoadStyleSheet(a[0].AsString())));});e.RegisterNative("ui_modern_style",[this](const std::vector<VekValue>&a){if(!a.empty())UseModernStyle(a[0].AsBool(true));return VekValue(modernStyleEnabled_);});
    e.RegisterNative("ui_animate",[this](const std::vector<VekValue>&a){if(a.size()<5)return VekValue(false);GuiAnimation x;x.nodeId=a[0].AsString();x.property=a[1].AsString();x.from=a[2].AsNumber();x.to=a[3].AsNumber();x.duration=a[4].AsNumber(.2);if(a.size()>5)x.ease=ParseEase(a[5].AsString());std::string err;return VekValue(StartAnimation(x,&err));});e.RegisterNative("ui_step",[this](const std::vector<VekValue>&a){if(!a.empty())Step(a[0].AsNumber());return VekValue();});e.RegisterNative("ui_snapshot",[this](const std::vector<VekValue>&){return Snapshot();});
    e.RegisterNative("ui_stats",[this](const std::vector<VekValue>&){auto s=Stats();VekMap m;m["revision"]=(double)s.revision;m["nodes"]=(double)s.nodeCount;m["visible"]=(double)s.visibleNodeCount;m["draw_commands"]=(double)s.drawCommandCount;m["modern_primitives"]=(double)s.modernPrimitiveCount;m["events"]=(double)s.queuedEventCount;m["animations"]=(double)s.activeAnimationCount;m["focused"]=s.focusedId;m["hovered"]=s.hoveredId;return VekValue(m);});
    e.RegisterNative("ui_draw_list",[this](const std::vector<VekValue>&){VekArray arr;for(auto&d:BuildDrawList()){VekMap m;m["type"]=(double)(int)d.type;m["node"]=d.nodeId;m["part"]=d.part;m["rect"]=RectToValue(d.rect);m["text"]=d.text;m["image"]=d.image;m["icon"]=d.icon;m["layer"]=d.layer;m["background"]=ColorToValue(d.style.background);m["foreground"]=ColorToValue(d.style.foreground);m["color"]=ColorToValue(d.color);m["thickness"]=d.thickness;m["value"]=d.value;m["data"]=d.data;arr.emplace_back(m);}return VekValue(arr);});
}

} // namespace vek
