#include <vek/VekRuntimeSystems.h>

#include <algorithm>
#include <cmath>
#include <numeric>

namespace vek {
namespace {
std::string GpuBackendName(GpuBackend b){switch(b){case GpuBackend::Direct3D11:return"d3d11";case GpuBackend::Direct3D12:return"d3d12";case GpuBackend::Vulkan:return"vulkan";case GpuBackend::Metal:return"metal";case GpuBackend::OpenGL:return"opengl";case GpuBackend::WebGPU:return"webgpu";case GpuBackend::Software:return"software";default:return"unknown";}}
GuiNodeType ParseGuiType(const std::string&s){static const std::unordered_map<std::string,GuiNodeType>m={{"window",GuiNodeType::Window},{"panel",GuiNodeType::Panel},{"label",GuiNodeType::Label},{"button",GuiNodeType::Button},{"toggle",GuiNodeType::Toggle},{"slider",GuiNodeType::Slider},{"progress",GuiNodeType::Progress},{"text_input",GuiNodeType::TextInput},{"image",GuiNodeType::Image},{"list",GuiNodeType::List},{"scroll",GuiNodeType::Scroll},{"canvas",GuiNodeType::Canvas},{"spacer",GuiNodeType::Spacer}};auto it=m.find(s);return it==m.end()?GuiNodeType::Panel:it->second;}
GameplayDefinitionType ParseGameplayType(const std::string&s){static const std::unordered_map<std::string,GameplayDefinitionType>m={{"ability",GameplayDefinitionType::Ability},{"input",GameplayDefinitionType::InputAction},{"camera",GameplayDefinitionType::CameraMode},{"item",GameplayDefinitionType::InventoryItem},{"quest",GameplayDefinitionType::Quest},{"spawn",GameplayDefinitionType::SpawnRule},{"state",GameplayDefinitionType::State},{"interaction",GameplayDefinitionType::Interaction},{"damage",GameplayDefinitionType::DamageType},{"team",GameplayDefinitionType::Team},{"objective",GameplayDefinitionType::Objective}};auto it=m.find(s);return it==m.end()?GameplayDefinitionType::State:it->second;}
}

FramePerformanceTracker::FramePerformanceTracker(std::size_t w){SetWindow(w);}void FramePerformanceTracker::SetWindow(std::size_t w){window_=std::clamp<std::size_t>(w,30,3600);while(samples_.size()>window_)samples_.pop_front();}void FramePerformanceTracker::Reset(){samples_.clear();frameCount_=0;}void FramePerformanceTracker::PushFrame(double dt,double cpu,double gpu){if(!std::isfinite(dt)||dt<=0)return;FrameSample s;s.frameMs=dt*1000.0;s.fps=1.0/dt;s.cpuMs=std::max(0.0,std::isfinite(cpu)?cpu:0.0);s.gpuMs=std::max(0.0,std::isfinite(gpu)?gpu:0.0);samples_.push_back(s);++frameCount_;while(samples_.size()>window_)samples_.pop_front();}
FrameStatistics FramePerformanceTracker::Statistics()const{FrameStatistics o;o.frameCount=frameCount_;if(samples_.empty())return o;o.fps=samples_.back().fps;std::vector<double>fps;fps.reserve(samples_.size());for(auto&s:samples_){o.averageFps+=s.fps;o.averageFrameMs+=s.frameMs;o.averageCpuMs+=s.cpuMs;o.averageGpuMs+=s.gpuMs;o.worstFrameMs=std::max(o.worstFrameMs,s.frameMs);fps.push_back(s.fps);}double n=(double)samples_.size();o.averageFps/=n;o.averageFrameMs/=n;o.averageCpuMs/=n;o.averageGpuMs/=n;std::sort(fps.begin(),fps.end());std::size_t count=std::max<std::size_t>(1,(std::size_t)std::ceil(fps.size()*0.01));o.onePercentLowFps=std::accumulate(fps.begin(),fps.begin()+count,0.0)/(double)count;return o;}
void FramePerformanceTracker::RegisterNatives(VekScriptEngine&e){e.RegisterNative("perf_stats",[this](const std::vector<VekValue>&){auto s=Statistics();VekMap m;m["fps"]=s.fps;m["avg_fps"]=s.averageFps;m["one_percent_low_fps"]=s.onePercentLowFps;m["frame_ms"]=s.averageFrameMs;m["cpu_ms"]=s.averageCpuMs;m["gpu_ms"]=s.averageGpuMs;m["worst_frame_ms"]=s.worstFrameMs;m["frames"]=(double)s.frameCount;return VekValue(std::move(m));});}

double GpuBudgetState::Utilization()const{return budgetBytes?std::clamp((double)usedBytes/(double)budgetBytes,0.0,64.0):0.0;}void GpuRuntimeInfo::SetCapabilities(GpuCapabilities c){caps_=std::move(c);}const GpuCapabilities&GpuRuntimeInfo::Capabilities()const{return caps_;}void GpuRuntimeInfo::SetBudget(GpuBudgetState b){budget_=b;}const GpuBudgetState&GpuRuntimeInfo::Budget()const{return budget_;}VekValue GpuRuntimeInfo::ToValue()const{VekMap m;m["adapter"]=caps_.adapterName;m["vendor"]=caps_.vendor;m["backend"]=GpuBackendName(caps_.backend);m["dedicated_bytes"]=(double)caps_.dedicatedMemoryBytes;m["shared_bytes"]=(double)caps_.sharedMemoryBytes;m["max_texture_size"]=(double)caps_.maxTextureSize;m["compute"]=caps_.computeShaders;m["ray_tracing"]=caps_.rayTracing;m["mesh_shaders"]=caps_.meshShaders;m["vrs"]=caps_.variableRateShading;m["bindless"]=caps_.bindlessResources;m["budget_bytes"]=(double)budget_.budgetBytes;m["used_bytes"]=(double)budget_.usedBytes;m["reserved_bytes"]=(double)budget_.reservedBytes;m["utilization"]=budget_.Utilization();return VekValue(std::move(m));}void GpuRuntimeInfo::RegisterNatives(VekScriptEngine&e){e.RegisterNative("gpu_info",[this](const std::vector<VekValue>&){return ToValue();});e.RegisterNative("gpu_supports",[this](const std::vector<VekValue>&a){if(a.empty())return VekValue(false);auto n=a[0].AsString();if(n=="compute")return VekValue(caps_.computeShaders);if(n=="ray_tracing")return VekValue(caps_.rayTracing);if(n=="mesh_shaders")return VekValue(caps_.meshShaders);if(n=="vrs")return VekValue(caps_.variableRateShading);if(n=="bindless")return VekValue(caps_.bindlessResources);return VekValue(false);});}

bool GuiDefinitionRegistry::Register(const GuiNodeDefinition&n,std::string*error){if(n.id.empty()||n.id.size()>128){if(error)*error="GUI id is empty or too long";return false;}if(nodes_.size()>=8192&&!nodes_.count(n.id)){if(error)*error="GUI registry limit reached";return false;}nodes_[n.id]=n;return true;}bool GuiDefinitionRegistry::RegisterValue(const VekValue&v,std::string*error){if(!v.IsMap()){if(error)*error="GUI definition must be a map";return false;}GuiNodeDefinition n;n.id=v.Get("id").AsString();n.type=ParseGuiType(v.Get("type").AsString());n.parentId=v.Get("parent").AsString();n.text=v.Get("text").AsString();n.x=(float)v.Get("x").AsNumber();n.y=(float)v.Get("y").AsNumber();n.width=(float)v.Get("width").AsNumber();n.height=(float)v.Get("height").AsNumber();n.minValue=(float)v.Get("min").AsNumber();n.maxValue=(float)v.Get("max").AsNumber(1);n.value=(float)v.Get("value").AsNumber();n.visible=v.Get("visible").IsNil()?true:v.Get("visible").AsBool();n.enabled=v.Get("enabled").IsNil()?true:v.Get("enabled").AsBool();n.focusable=v.Get("focusable").AsBool();n.data=v.Get("data").IsNil()?VekValue::Map():v.Get("data");return Register(n,error);}const GuiNodeDefinition*GuiDefinitionRegistry::Find(const std::string&id)const{auto i=nodes_.find(id);return i==nodes_.end()?nullptr:&i->second;}bool GuiDefinitionRegistry::Remove(const std::string&id){return nodes_.erase(id)!=0;}void GuiDefinitionRegistry::Clear(){nodes_.clear();}std::size_t GuiDefinitionRegistry::Size()const{return nodes_.size();}std::vector<std::string>GuiDefinitionRegistry::ChildrenOf(const std::string&p)const{std::vector<std::string>r;for(auto&[id,n]:nodes_)if(n.parentId==p)r.push_back(id);std::sort(r.begin(),r.end());return r;}void GuiDefinitionRegistry::RegisterNatives(VekScriptEngine&e){e.RegisterNative("gui_define",[this](const std::vector<VekValue>&a){std::string err;return VekValue(!a.empty()&&RegisterValue(a[0],&err));});e.RegisterNative("gui_count",[this](const std::vector<VekValue>&){return VekValue((double)Size());});e.RegisterNative("gui_exists",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Find(a[0].AsString()));});e.RegisterNative("gui_remove",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Remove(a[0].AsString()));});}

bool GameplayDefinitionRegistry::Register(const GameplayDefinition&d,std::string*error){if(d.id.empty()||d.id.size()>128){if(error)*error="gameplay id is empty or too long";return false;}if(definitions_.size()>=8192&&!definitions_.count(d.id)){if(error)*error="gameplay registry limit reached";return false;}definitions_[d.id]=d;return true;}bool GameplayDefinitionRegistry::RegisterValue(const VekValue&v,std::string*error){if(!v.IsMap()){if(error)*error="gameplay definition must be a map";return false;}GameplayDefinition d;d.id=v.Get("id").AsString();d.type=ParseGameplayType(v.Get("type").AsString());d.displayName=v.Get("display_name").AsString();d.enabled=v.Get("enabled").IsNil()?true:v.Get("enabled").AsBool();d.cooldown=(float)v.Get("cooldown").AsNumber();d.duration=(float)v.Get("duration").AsNumber();d.priority=(int)v.Get("priority").AsNumber();d.properties=v.Get("properties").IsNil()?VekValue::Map():v.Get("properties");return Register(d,error);}const GameplayDefinition*GameplayDefinitionRegistry::Find(const std::string&id)const{auto i=definitions_.find(id);return i==definitions_.end()?nullptr:&i->second;}bool GameplayDefinitionRegistry::Remove(const std::string&id){return definitions_.erase(id)!=0;}void GameplayDefinitionRegistry::Clear(){definitions_.clear();}std::size_t GameplayDefinitionRegistry::Size()const{return definitions_.size();}void GameplayDefinitionRegistry::RegisterNatives(VekScriptEngine&e){e.RegisterNative("gameplay_define",[this](const std::vector<VekValue>&a){std::string err;return VekValue(!a.empty()&&RegisterValue(a[0],&err));});e.RegisterNative("gameplay_count",[this](const std::vector<VekValue>&){return VekValue((double)Size());});e.RegisterNative("gameplay_exists",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Find(a[0].AsString()));});e.RegisterNative("gameplay_remove",[this](const std::vector<VekValue>&a){return VekValue(!a.empty()&&Remove(a[0].AsString()));});}

void RuntimeProfiler::Record(const std::string&n,double ms){if(n.empty()||!std::isfinite(ms))return;auto&z=zones_[n];z.name=n;z.milliseconds+=std::max(0.0,ms);++z.calls;}void RuntimeProfiler::Reset(){zones_.clear();}std::vector<ProfilerZoneSample>RuntimeProfiler::Snapshot()const{std::vector<ProfilerZoneSample>r;for(auto&[_,z]:zones_)r.push_back(z);std::sort(r.begin(),r.end(),[](auto&a,auto&b){return a.milliseconds>b.milliseconds;});return r;}VekValue RuntimeProfiler::ToValue()const{VekArray a;for(auto&z:Snapshot()){VekMap m;m["name"]=z.name;m["ms"]=z.milliseconds;m["calls"]=(double)z.calls;a.emplace_back(std::move(m));}return VekValue(std::move(a));}void RuntimeProfiler::RegisterNatives(VekScriptEngine&e){e.RegisterNative("profiler_snapshot",[this](const std::vector<VekValue>&){return ToValue();});e.RegisterNative("profiler_reset",[this](const std::vector<VekValue>&){Reset();return VekValue(true);});}
void RuntimePlatformPack::RegisterNatives(VekScriptEngine&e){performance.RegisterNatives(e);gpu.RegisterNatives(e);gui.RegisterNatives(e);gameplay.RegisterNatives(e);profiler.RegisterNatives(e);}

} // namespace vek
