#include "VekVehicleEditorRules.h"
#include "VekSecuritySystem.h"
#include <VekGameSystems.h>
#include <algorithm>
#include <cmath>
#include "VekHostSecurity.h"
std::string VekVehicleEditorRules::ModeName(vek::GameMode m){return m==vek::GameMode::Sandbox?"sandbox":"survival";}
bool VekVehicleEditorRules::Initialize(const std::string&p){file=p;return LoadInternal();}
bool VekVehicleEditorRules::LoadInternal(){VekScriptEngine fresh;ApplyGameVekSecurityPolicy(fresh);VekRegisterStandardLibrary(fresh);vek::VekRegisterGameplayLibrary(fresh);vek::VekRegisterVehicleEditorLibrary(fresh);fresh.SealNativeRegistry();auto verified=VekSecuritySystem::VerifyScript(file,file+".sig");if(!verified.ok){loaded=false;error=verified.error;return false;}if(!fresh.LoadSource(verified.source,file)){loaded=false;error=fresh.LastError();return false;}const char*req[]={"part_cost","part_unlocked","max_parts","grid_steps","placement_valid","placement_status","attachment_compatible","build_valid","build_message","power_warning","upgrade_cost","infinite_fuel","free_placement_allowed","symmetry_allowed"};for(auto fn:req)if(!fresh.HasFunction(fn)){loaded=false;error=std::string("VEK vehicle_editor.vek missing fn ")+fn;return false;}engine=std::move(fresh);loaded=true;error.clear();return true;}
bool VekVehicleEditorRules::ReloadScript(){if(!CanHotReload()){error="VEK Guard: editor hot reload disabled";return false;}return LoadInternal();}bool VekVehicleEditorRules::CanHotReload()const{return VekSecuritySystem::IsDevelopmentMode();}
float VekVehicleEditorRules::PartCost(vek::GameMode m,float b)const{if(!loaded)return m==vek::GameMode::Sandbox?0:b;return std::clamp((float)engine.Call("part_cost",{ModeName(m),b}).AsNumber(b),0.0f,1000000.0f);}bool VekVehicleEditorRules::PartUnlocked(vek::GameMode m,int l,int r,bool s)const{if(!loaded)return m==vek::GameMode::Sandbox||(!s&&l>=r);return engine.Call("part_unlocked",{ModeName(m),l,r,s}).AsBool();}int VekVehicleEditorRules::MaxParts(vek::GameMode m)const{if(!loaded)return m==vek::GameMode::Sandbox?800:300;return std::clamp((int)engine.Call("max_parts",{ModeName(m)}).AsNumber(),16,2000);}bool VekVehicleEditorRules::PlacementValid(vek::GameMode m,float x,float z,int n)const{if(!loaded)return std::fabs(x)<=42&&std::fabs(z)<=42&&n<MaxParts(m);return engine.Call("placement_valid",{ModeName(m),x,z,n}).AsBool();}
std::vector<float>VekVehicleEditorRules::GridSteps()const{std::vector<float>o={1,0.5f,0.25f,0.1f,0.05f};if(!loaded)return o;auto v=engine.Call("grid_steps");if(auto*a=v.AsArray()){o.clear();for(auto&x:*a){float f=(float)x.AsNumber();if(f>=0.01f&&f<=5)o.push_back(f);}if(o.empty())o={0.25f};}return o;}
vek::PlacementResult VekVehicleEditorRules::PlacementStatus(bool i,bool c,float d)const{if(!loaded)return i?vek::PlacementResult::Invalid:(!c&&d>2.5f?vek::PlacementResult::Warning:vek::PlacementResult::Allowed);std::string s=engine.Call("placement_status",{i,c,d}).AsString();if(s=="invalid")return vek::PlacementResult::Invalid;if(s=="warning")return vek::PlacementResult::Warning;return vek::PlacementResult::Allowed;}
bool VekVehicleEditorRules::AttachmentCompatible(const std::string&a,const std::string&b)const{if(!loaded)return a==b;return engine.Call("attachment_compatible",{a,b}).AsBool();}
bool VekVehicleEditorRules::FreePlacementAllowed(vek::GameMode m)const{return !loaded?m==vek::GameMode::Sandbox:engine.Call("free_placement_allowed",{ModeName(m)}).AsBool();}bool VekVehicleEditorRules::SymmetryAllowed(vek::GameMode m)const{return !loaded?true:engine.Call("symmetry_allowed",{ModeName(m)}).AsBool();}
bool VekVehicleEditorRules::BuildValid(vek::GameMode m,int s,int e,int seats,int wheels,int movement,int money,float cost)const{if(!loaded)return s>=1&&e>=1&&seats>=1&&(wheels>=3||movement>=1)&&(m==vek::GameMode::Sandbox||money>=cost);return engine.Call("build_valid",{ModeName(m),s,e,seats,wheels,movement,money,cost}).AsBool();}std::string VekVehicleEditorRules::BuildMessage(vek::GameMode m,int s,int e,int seats,int wheels,int movement,int money,float cost)const{if(!loaded)return BuildValid(m,s,e,seats,wheels,movement,money,cost)?"Build ready.":"Build requirements not met.";return engine.Call("build_message",{ModeName(m),s,e,seats,wheels,movement,money,cost}).AsString();}std::string VekVehicleEditorRules::PowerWarning(float mass,float power)const{if(!loaded)return power/std::max(1.0f,mass)<20?"LOW POWER-TO-WEIGHT":"";return engine.Call("power_warning",{mass,power}).AsString();}float VekVehicleEditorRules::UpgradeCost(vek::GameMode m,float b)const{return !loaded?(m==vek::GameMode::Sandbox?0:b):std::max(0.0f,(float)engine.Call("upgrade_cost",{ModeName(m),b}).AsNumber(b));}bool VekVehicleEditorRules::InfiniteFuel(vek::GameMode m)const{return !loaded?m==vek::GameMode::Sandbox:engine.Call("infinite_fuel",{ModeName(m)}).AsBool();}
